### PR TITLE
Save only one session when type changes

### PR DESCRIPTION
**Pull request by jrjohnson**
We were saving every session connected to a type.

### CODE REVIEW

**Comment by saschaben** [comment]
local build throws Uncaught TypeError: session.save is not a function

**Comment by thecoolestguy** [comment]
I am not able to save a session type change. Console returns: Uncaught Error: Assertion Failed: You cannot add 'undefined' records to the sessionType.sessions relationship (only 'session' allowed)

**Comment by jrjohnson** [comment]
Ok - I think I fixed this.  Little bit of a race condition.  Please test again.

**Comment by saschaben** [comment]
Appears to be better now. ILM still busted of course, but this granularly looks okey dokey.

**Pull request merged**
