### PR TITLE
Update ember-cli to 1.13.8

### PR DESCRIPTION
**Pull request by jrjohnson**
Should be non-breaking changes to ember and ember data.  Required some changes to tests, time picking and inflection.  Needs a through click through to ensure nothing else is broken.

### CODE REVIEW

**Comment by saschaben** [comment]
Well, a basic clickthru shows (so far) no major issues, but all text input fields now display a reduced height and reduced font size --- this includes calendar select inputs.

**Comment by jrjohnson** [comment]
Good catch, I think I solved that.

**Comment by saschaben** [comment]
yup. all better now.

**Comment by jrjohnson** [comment]
OK - well as a consequence of sauce doing weird stuff I've removed our browser tests from travis.  This is now ready for @thecoolestguy to code review.

**Pull request merged**
