### PR TITLE
upgraded ui-select to v0.0.10

### PR DESCRIPTION
**Pull request by djvoa12**

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben can you make sure that adding users to learner groups and bulk editing still works and star?

**Comment by saschaben** [comment]
adding users appears to function correctly.

bulk edit has display error in control (below)
err2

my initial bulk test threw a bunch of errors, but I can't reproduce so I think it was cache.

**Comment by djvoa12** [comment]
You have to `npm install` to get the latest version.

**Comment by saschaben** [comment]
ah. got it.

Everything looks good now (after `npm install`, duh.) One minor fix: the label on the bulk edit control should be plural:  "Remove/Switch _learners_ to..." not learner. Even for a single selection, the implication should be "move all the selected _items_ to somewhere else".

**Comment by saschaben** [comment]
@djvoa12 if you can tweak that label, quickly, let's go ahead -- otherwise let's add an enhancement ticket and I'll star this one.

**Comment by djvoa12** [comment]
jesus finally green

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@homu r+

**Comment by jrjohnson** [comment]
@homu retry

**Pull request merged**
