### PR TITLE
allow HTML Editor to grow to take up remaining space

### PR DESCRIPTION
**Pull request by michaelchadwick**
Fixes ilios/ilios#4320

### CODE REVIEW

**Review by stopfstedt — APPROVED** [review]
code reviewed and viz reviewed wherever we embed the WYSIWYG editor. LGTM.

**Comment by stopfstedt** [comment]
@dartajax please give this another look-over. anywhere we have Froala on the screen. thanks.

**Comment by dartajax** [comment]
In testing the PR, I found that with this new wider format, the line returns are being reflected as they should - see below

image

**Comment by dartajax** [comment]
This is on demo ...

image

**Review by dartajax — APPROVED** [review]
I like this. I found some unrelated fixes that were pushed out in the recent froala upgrade while testing this PR. All good - gonna merge soon and reference the froala upgrade PR in the notes.

**Comment by dartajax** [comment]
here is the froala upgrade to which I was referring ...

refs# https://github.com/ilios/frontend/pull/7884

**Pull request merged**
