### PR TITLE
one-way-controls replacement in user profile bio form.

### PR DESCRIPTION
**Pull request by stopfstedt**
replaced one-way-controls with markup equivalents in "user profile bio" form.

refs #3466 

this form here:

selection_454

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 2c0dffe63c6e8aa43c50b1ee84805357d14df795

https://deploy-preview-3504--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 0675359820a37a6c692810d863fa62997b40a688

https://deploy-preview-3504--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
Even though I approved this, pls do not merge (hence the tag). The validation needs some work -`onfocusout` event handler needs to call up the validation messages before the user has to try to save his / her work to find out what's missing.

**Comment by dartajax** [comment]
LGTM

**Pull request merged**
