### PR TITLE
correct menu sizing and transforms

### PR DESCRIPTION
**Pull request by saschaben**
update slide out menu to avoid overlay when in interstitial sizing

### CODE REVIEW

**Comment by saschaben** [comment]
@thecoolestguy please review my css mods here. I think it should be solid.

**Comment by saschaben** [comment]
BTW, I believe this is not going to function properly in Safari 9.1, and will need a user test in IE.

**Comment by saschaben** [comment]
fixes #1781

**Comment by dartajax** [comment]
Seems to work fine in IE 11.

**Pull request merged**
