### PR TITLE
Upgrade Mirage

### PR DESCRIPTION
**Pull request by jrjohnson**
Updates ember-cli-mirage to v 0.2 and updates tests to match.

Superseds #1751

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit dc0123ec54276e8cc7cbc32aece351bda043a770

https://deploy-preview-2774--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
The new mirage 0.3.3 automatically generates models so we can pull most of that code out.

**Comment by stopfstedt** [comment]
we need to get off of Mirage 1.x before we can to Ember 3, upgrade or get out of it altogether.

Reason:
Mirage 1.x relied on `this.container` to be present. Direct access to the container API has been [deprecated since Ember 2.3 and will be removed with Ember 3.0.0](https://emberjs.com/deprecations/v2.x/#toc_injected-container-access)

refs #3289

**Comment by jrjohnson** [comment]
Replaced by #3379

**Pull request closed without merging**
