### PR TITLE
Fix some Jumpy Cursor Issues

### LINKED ISSUE #2045: Jumpy Search Cursor
after the upstream fix to the search component, we still have jumpy cursor issue in on place in the system

jumpy_cursor

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #2045

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please review.

**Comment by dartajax** [comment]
In the screen shot below 

image

I have my cursor after the zero (minutes).  I would like to "delete" this zero and type in "15".  When I hit the backspace key on my keyboard, nothing happens.  The same is true if I use the arrow key (left arrow) to put the cursor in front of (before) the zero character.  When I now try to delete the zero by using the delete key on my keyboard, same as with backspace, nothing happens.  I am aware that if I decide to type in "15", regardless of where my cursor is, that it will accept my entry of "15".  It is a bit confusing though as a user.

**Comment by dartajax** [comment]
Other than what I pointed out above, I am not noticing any jumpy behavior.

**Comment by jrjohnson** [comment]
Good feedback @dartajax this is going to require some additional refactoring of this form.  Can you create that as a separate ticket.

**Comment by jrjohnson** [comment]
I have reviewed my own code here and it LGTM 👍

**Pull request merged**
