### PR TITLE
Don't display archived courses or program years

### LINKED ISSUE #2065: Don't display archived items
Courses and ProgramYear which are archived are currently showing up.

### PR DESCRIPTION
**Pull request by jrjohnson**
These should not be in the list, that is why they are archived.

Fixes #2065

### CODE REVIEW

**Comment by saschaben** [comment]
@jrjohnson looks good for course. but no way to test for program year -- none are currently archived. can you or @thecoolestguy tweak the data in demo3 to have a few? 

For testing purposes, please set to archived program years 19 and 56, associated with program 12.

**Comment by thecoolestguy** [comment]
I've set the program years 12 and 56 to archived == 1 in the demo database... Let me know if I should set this nightly, so it is reflected as such in demo build/downloadable db.

**Comment by saschaben** [comment]
👍 

Archived courses now hidden from list
Archived programs now hidden from list
All is PASSED

👍

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
