### PR TITLE
Add Course Publication Workflow

### LINKED ISSUE #141: Add publish workflow to course details
@jenzweben please attach your mock for this process.

### LINKED ISSUE #229: Dropdowns on Course List, and Sessions List on Course Detail Page - BUG
When you select something from the dropdown then click outside to close it (taking no action) the label for the item you selected is displaying on the dropdown button instead of the actions icon

screen shot 2015-02-26 at 10 08 14 am

### PR DESCRIPTION
**Pull request by jrjohnson**
Allows courses to be scheduled, published, and unpublished.
Displays publication issues on a separate route.

Fixes #141
Fixes #229

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/237" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
not ready.

The workflow is broken on publish / unpublish and throws errors:

ilios 2015-02-27 10-53-50

unable to unpublish a scheduled course.
unable to publish a course with missing items (only able to set to scheduled, and once set to scheduled, am able to publish)
Once scheduled, unpublish actually sets to published.

(We still need a "publish all" control as well)

For course, workflow is:

If a course is missing cohort OR objective OR topic OR mesh, alert for review or allow for scheduled.
> On review, provide a "publish anyway" button
If a course is complete for the above, allow for scheduled or publish.

**Comment by saschaben** [comment]
For publish dropdown selections, please follow format from the mock in #141 

The "publish as-is" option is required, esp.  if we are providing the visual review as shown in the separate route.

scheduled option is always available; the variable cases are review and publish as-is (as opposed to just publish)

**Comment by jrjohnson** [comment]
@saschaben  
Publish as is is not available when *required* options are missing (cohort, startDate, endDate).  You can only schedule and review in those cases.  
Alternatively when ALL conditions are met, publish as is becomes simple publish.

**Comment by saschaben** [comment]
OK. workflow issues were from bad build. BUT: still throwing error when attempting to unpublish a published course from the missing items review page:

error1

error2

**Comment by jrjohnson** [comment]
@saschaben - can you give me a specific course for the unpublish issue?

**Comment by saschaben** [comment]
Try using anesthesia (first course in the list)

**Comment by jrjohnson** [comment]
Ok - turned out to have nothing to do with this code and was an issue from #216.  Should be fixed now.

**Comment by saschaben** [comment]
Looks good. Let's discuss the potential of moving the "back to course" link down from the top of the overview, and onto the top of the review section for the missing items review mode. Should be able to make this work if we can integrate the pattern in use for session.

Code review & Merge!

**Pull request merged**
