### PR TITLE
yanks publication status from programs and program-years.

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #3675 
refs #4416

### CODE REVIEW

**Comment by dartajax** [comment]
LGTM - the whole concept of publishing program and program year is gone

**Comment by stopfstedt** [comment]
> We need to have a button available to "publish" or "activate" the legacy "not published" years. "Activate" would work well.
> 
> image

i thought the whole notion of "published" goes away?

**Comment by stopfstedt** [comment]
@dartajax how about a modified publish status dropdown to only include a non-reversible "publish" option, when the current status is in draft/tdb?

**Comment by stopfstedt** [comment]
scrapped.

**Pull request closed without merging**
