### PR TITLE
Improve session list

### PR DESCRIPTION
**Pull request by jrjohnson**
Using the ember-light-table addon we can add some features our users
have been missing like fixed table header and improved loading of very
large session lists without needing to page the results first.

Todo:
- [x] Restore expand row to see offering summary
- [x] Fixup tests for new structure
- [x] Add sort icons (waiting for new version of ember-light-table which will activate the iconSortable already in the code)

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 117972bab65477ba9cf7a64f3b497d26b9d7906c

https://deploy-preview-3154--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
Can we get the sorting icons back? 

image

**Comment by jrjohnson** [comment]
@dartajax restoration of the sort icons has to wait for a new version of the table addon I'm using here. Is that a show stopper?

This is ready for another review. It should now be feature complete with the original session list.

**Comment by dartajax** [comment]
1. The header row gets weird when you sort by "Status". 

2. I am okay with the sort icons not being there. I know they will be coming back soon.

3. The Learner Groups are not counting up correctly for Independent Learning sessions.

image

image

image

**Comment by jrjohnson** [comment]
Holding off on a merge until post release to space out big feature adds and give time for the guide to be updated.

**Comment by jrjohnson** [comment]
@dartajax give it another look, sort icons are back, groups are fixed and there is some more space for the status so it looks better.

**Comment by dartajax** [comment]
LGTM 👍

**Comment by saschaben** [comment]
- ILMs are not showing due by date value in "first offering" column
- right margin of title column overruns session type column for courses with long names
- expansion icon on left is a little small to easily target with cursor; needs to be more user-friendly accessible
- entire scrollbox is SMALL. Shows only 10 rows at a time compared to the min. 25 we have now. Feels cramped. Is there any reason not to increase the height and number of rows painted?

**Comment by saschaben** [comment]
overlap

ilm

**Comment by jrjohnson** [comment]
@saschaben feedback handled, ready for another review.

**Comment by saschaben** [comment]
Latest updates look great to me :+1:

Let's not forget to add a follow-up ticket to address filter lag.

**Comment by jrjohnson** [comment]
Alrighty then. Just needs a code review from @thecoolestguy, @stopfstedt or @gboushey.

**Pull request merged**
