### PR TITLE
event notes passed in

### LINKED ISSUE #881: event detail page should display citation / LM notes
learning materials include instructional notes which may or may not be exposed to learners. These notes should be

A) included in the individual learning material display on the event detail page;
B) checked for the display flag and shown/hidden according to user role appropriately.

### PR DESCRIPTION
**Pull request by djvoa12**
Event notes are only passed in when `publicNotes` property is `true`.

Fixes #881 
Calendar PR: https://github.com/ilios/calendar/pull/9

### CODE REVIEW

**Comment by saschaben** [comment]
not currently seeing notes: proxied to demo at  `http://localhost:4200/events/U20151110O70621`. First LM should have a note "this is a student note".

`http://localhost:4200//courses/791/sessions/25462`

**Comment by djvoa12** [comment]
It a work in progress. The calendar PR need to be merged and re-versioned for this to work.

**Comment by saschaben** [comment]
Got it.

**Comment by jrjohnson** [comment]
@djvoa12 you can now update package.json to ilios-calendar 2.2.0 and we should be off and running.

**Comment by djvoa12** [comment]
@jrjohnson done

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
