### PR TITLE
Working session objective manager

### PR DESCRIPTION
**Pull request by jrjohnson**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/210" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
is the star on this for code review? If so please assign to me for UI review

**Comment by saschaben** [comment]
cannot un-select objective once checked.
also:

we have some lag time on the checkbox action as well
we should be applying the same slide-in animation for this as we are for session/session list.

**Comment by jrjohnson** [comment]
@saschaben are you sure about un-checking?  It works for me.  
We can't slide these in right now.  Too many layers to manage.  I'm 100% behind getting that going in a future release, but it adds significant complexity and will set us back weeks.

The lag time is also something to add to the list, but I want to get it up onto the real API before we start looking at which things need to perform better.

**Comment by saschaben** [comment]
definitely can't un-check right now @jrjohnson

**Comment by jrjohnson** [comment]
@saschaben - updated, give this another look.

**Comment by saschaben** [comment]
check uncheck issue looks to be resolved. yay.
we still have the selected items dropping to the bottom of the list: they should stay in whatever sort order they are in to begin with (ID, alpha, whatever). Selected vs. unselected is not a good default ordering state.

**Comment by jrjohnson** [comment]
@saschaben - ok they are sorting by title now.

**Comment by saschaben** [comment]
right-o. let's code check and merge. We are still having some collision issues with the checkbox saves if someone clicks thru too quickly but we will address that as a bug later.

**Comment by saschaben** [comment]
awaiting code review ninjastar.

**Pull request merged**
