### PR TITLE
Dashboard API fixes

### LINKED ISSUE #1125: Courses subject reports failing
The API expects filter terms to be pluralized and we are sending singular.  This causes filters with a course subject to fail.

### PR DESCRIPTION
**Pull request by jrjohnson**
Use a query to gather user courses.  Should speed up that load, time will tell.
Fixed a problem with the dashboard route that was causing it not to load for unauthenticated users.

Fix the query to get report results to use a camel cased pluralized name.

Fixes #1125

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please check dashboard loads.  The courses reports actually return some data some of the time and the my courses list loads.  I think all of this will work proxying off of demo.

**Comment by saschaben** [comment]
Dashboard proxied to demo with this PR currently returns 500 error "Adapter operation failed" (x2)

**Comment by saschaben** [comment]
```html

GET /api/v1/courses?filters%5Busers%5D%5B%5D=16 500 241.673 ms - 46
POST /errors 204 227.133 ms - 0
POST /errors 204 222.383 ms - 0
GET /auth/config 200 187.768 ms - 26
POST /auth/login 400 879.658 ms - 57
POST /auth/login 200 862.186 ms - 229
GET /auth/whoami 200 216.989 ms - 13
GET /api/v1/users/16 200 240.607 ms - 677
GET /api/v1/academicyears 200 395.624 ms - 251
GET /api/v1/userroles?filters%5Bid%5D%5B%5D=1&filters%5Bid%5D%5B%5D=2&filters%5Bid%5D%5B%5D=3&limit=1000000 200 363.829 ms - 106
GET /api/v1/schools/1 200 435.581 ms - -
GET /api/v1/permissions?filters%5Bid%5D%5B%5D=34&filters%5Bid%5D%5B%5D=35&filters%5Bid%5D%5B%5D=705&filters%5Bid%5D%5B%5D=706&filters%5Bid%5D%5B%5D=707&filters%5Bid%5D%5B%5D=620&filters%5Bid%5D%5B%5D=621&filters%5Bid%5D%5B%5D=622&filters%5Bid%5D%5B%5D=623&filters%5Bid%5D%5B%5D=624&filters%5Bid%5D%5B%5D=625&limit=1000000 200 228.612 ms - 1010
GET /api/v1/schools?filters%5Bid%5D%5B%5D=2&filters%5Bid%5D%5B%5D=3&filters%5Bid%5D%5B%5D=4&filters%5Bid%5D%5B%5D=5&filters%5Bid%5D%5B%5D=6&limit=1000000 200 498.748 ms - -
GET /api/v1/userevents/16?from=1448006444&to=1450684784 200 233.564 ms - 17
GET /api/v1/courses?filters%5Busers%5D%5B%5D=16 500 230.501 ms - 46
POST /errors 204 214.800 ms - 0
POST /errors 204 231.709 ms - 0
```

**Comment by jrjohnson** [comment]
@thecoolestguy please review.  I think this is working against a current version of the API, but probably just not against what is on demo.  On the other hand we can't update demo until this gets merged... so lets review and merge this and we can solve any problems later.

**Comment by thecoolestguy** [comment]
@homu r+

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
