### PR TITLE
show more details in MeSH picker

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #899

### CODE REVIEW

**Comment by stopfstedt** [comment]
selection_018

**Comment by saschaben** [comment]
this is looking really really good. We should probably think about how to deal with the scope notes and the current ellipsis cutoff --- at this stage, there's no way to expand the note fully -- but the current responsiveness and data display is awesome as is.

**Comment by stopfstedt** [comment]
@saschaben thanks for the feedback. would displaying the full scope notes be an option?

meanwhile i fixed all regressions in existing tests that were introduced by these markup changes. 

still need to put the newly displayed data points under test coverage. but really close to being done now.

**Comment by saschaben** [comment]
@stopfstedt I'm not sure we want to allow full scope notes without limit, as I'm not sure how long they might turn out to be. But perhaps a longer string prior to truncation; right now you have it set to truncate at ~65 chars. Why not extend that to 250 and call it a day. Anything over that is prolly too much for a body to pay attention to anyway. we can revisit later.

**Comment by stopfstedt** [comment]
@jrjohnson please review. @saschaben see follow-up #939. thanks!

**Comment by jrjohnson** [comment]
@homu r+

**Comment by jrjohnson** [comment]
Moved ahead as it looks like functional review already happened.

**Comment by saschaben** [comment]
@stopfstedt does this ticket override #899, or is that still a separate issue?

**Comment by stopfstedt** [comment]
@saschaben :this fixes #899

**Pull request merged**
