### PR TITLE
trim user input and data points when filtering.

### PR DESCRIPTION
**Pull request by stopfstedt**

### CODE REVIEW

**Comment by dartajax** [comment]
image

**Comment by stopfstedt** [comment]
> image

different bug, out of scope. see #5631

**Comment by dartajax** [comment]
I think I removed the wrong screen shot - sorry about that. I know what this entails though and will be re-testing it now.

**Review by dartajax — APPROVED** [review]
This is now quite excellent.

**Review by jrjohnson — APPROVED** [review]

**Pull request merged**
