### PR TITLE
nav-links in flyout now sticky and stay on top when page scrolled down

### PR DESCRIPTION
**Pull request by michaelchadwick**
Fixes ilios/ilios#4293

### CODE REVIEW

**Comment by michaelchadwick** [comment]
Btw, the `bottom: 0` was required for Firefox (`top: 0` seemed to be good enough for Chrome) to not have vertical-alignment glitches when resizing the browser window.

**Comment by jrjohnson** [comment]
I'm not getting any stickiness at all in Safari 18.0 
Screenshot 2024-09-30 at 9 11 31 AM

**Comment by michaelchadwick** [comment]
@jrjohnson Nice catch. Fix has been made.

**Review by jrjohnson — APPROVED** [review]
Love it!

**Pull request merged**
