### PR TITLE
Load instructors directly from event

### LINKED ISSUE #1197: Align calendar with new events API data
ilios/ilios#1172 introduces instructor names into userevents and schoolevents we need to update the calendar to work with this data.

### PR DESCRIPTION
**Pull request by jrjohnson**
The new user and school events endpoints return a list of instructors
directly.

Fixes #1197

### CODE REVIEW

**Comment by saschaben** [comment]
event display doesn't seem to be showing instructor at all....

**Comment by jrjohnson** [comment]
Yea, my bad.  Can't be tested on demo as it requires a change we just made.

**Comment by saschaben** [comment]
:+1:

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
