### PR TITLE
Re-style pie and donut chart tooltip

### PR DESCRIPTION
**Pull request by gabycampagna**

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit aaaca3bad7d589626c988aa0cda9bf92a2b6a281

https://deploy-preview-2790--ilios-frontend.netlify.com

**Comment by gabycampagna** [comment]
Not sure why this commit didn't pass tests.

**Comment by saschaben** [comment]
looks like a browser failure to launch in travis:

```
ok 840 Chrome 54.0 - Exam Partition #1 - Integration | Component | learnergroup instructor manager: can remove groups
not ok 841 Chrome - error
    ---
        message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            Stderr: 
             Xlib:  extension "RANDR" missing on display ":99.0".
            [17099:17153:0324/185151:ERROR:bus.cc(434)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
            Xlib:  extension "RANDR" missing on display ":99.0".
            [17259:17259:0324/185152:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
            
            
        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 30s. testem.js not loaded?' }
            { type: 'error',
              text: 'Xlib:  extension "RANDR" missing on display ":99.0".\n[17099:17153:0324/185151:ERROR:bus.cc(434)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused\nXlib:  extension "RANDR" missing on display ":99.0".\n[17259:17259:0324/185152:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. \n' }
```

**Comment by gabycampagna** [comment]
Thank you!  I just changed font size for tool tips, so running another test...

**Pull request merged**
