### PR TITLE
Add a calendar to the offering editor

### LINKED ISSUE #1009: Add/activate calendar toggle to header in offerings area
Calendar toggle removed to cleanup before initial launch, needs to be put back in and activated

see changes made to #760

### PR DESCRIPTION
**Pull request by jrjohnson**
This makes it possible to see what else might conflict with a specific offering as it is created or edited.

WIP: 
- [x] Needs initial functional review from @saschaben
- [x] Might need a toggle to turn it off

Supersedes: #3202
Fixes #1009

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 17285347022b0e85794719d40585ae936d0261e8

https://deploy-preview-3285--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
required for launch:
- back/forward week navigation links
- show/hide toggle (default = hide. this calendar is big!)
- filter for "show this session only" / "show all other events"

I don't think we can fly without those three things at minimum.

**Comment by jrjohnson** [comment]
@saschaben back / forward is the only one that I'm not sure about. The calendar is centered on the date of the current offering. If you go back does that change the offering date? If not what would be the purpose of going back a week as it relates to scheduling this event?

**Comment by saschaben** [comment]
@jrjohnson ahh. then that means we have a bug still: if you open an offering, the calendar currently focuses on currentWeek, not on offeringDate. let's fix that and I will review again.

**Comment by jrjohnson** [comment]
@saschaben this is ready for review again (still needs tests). You can now toggle the calendar on and off and you can also toggle individual filter sets.  Let me know what you think.

**Comment by saschaben** [comment]
At first glance this is looking really good. I have a few comments on language and display that we should review when I am in office. But this is very close to ready.

**Comment by saschaben** [comment]
label thoughts:

ilios courses and sessions 2017-10-23 13-49-36

**Comment by saschaben** [comment]
ISSUE: calendar header style issue in "new offering" cal:

caloffering

**Pull request merged**
