### PR TITLE
removed unnatural scrolling related to objectives

### LINKED ISSUE #729: Select Parent Objective for Session objective scrolls to wrong target
If the course details are open, selecting a session parent objective will scroll you to the top of the course objectives, rather than to the opened select parent objective panel for the session,

### PR DESCRIPTION
**Pull request by djvoa12**
For courses and sessions:
- [x] removed scroll for `Add New` button
- [x] removed scroll that occurs when `undo/cancel` button is clicked

Fixes #729

### CODE REVIEW

**Comment by jrjohnson** [comment]
I think this is functionality that we need.  We have to orient the users back into the area of the screen that they left when opening the objective manager.

**Comment by jrjohnson** [comment]
oh 729 - I think that is about the target of the scroll not the scroll itself.

**Comment by djvoa12** [comment]
That's correct.

**Comment by jrjohnson** [comment]
:+1: @homu r+

**Pull request merged**
