### PR TITLE
Handle Locked Courses

### LINKED ISSUE #1266: Locked Courses Need To Have An Indication Of That Fact
Since we have not gotten to locking, archiving, and rolling over courses, there is currently no indication that a course is locked.  The user will an error when they try and access that course but the course should either be in read-only mode or at a minimum, contain a visual indicator that the course is locked.

### PR DESCRIPTION
**Pull request by jrjohnson**
Prevents any editing on locked courses by not showing the buttons or actions.

Fixes #1266

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this is ready to be tested.

**Comment by saschaben** [comment]
ROCK AND ROLL!

(note to self: at some point we should look to replace the session edit icon in this mode to a version of the eyeball. but not important now.)

**Comment by saschaben** [comment]
@stopfstedt please code review and merge if ready.

**Comment by stopfstedt** [comment]
please remove edit and delete actions from session-list of locked courses.

selection_080

**Comment by stopfstedt** [comment]
otherwise LGTM

**Comment by jrjohnson** [comment]
@stopfstedt  Fixed.  Good catch.

**Pull request merged**
