### PR TITLE
added course status indicator colors, refs #52

### PR DESCRIPTION
**Pull request by jenzweben**

### CODE REVIEW

**Comment by saschaben** [comment]
looks like we have a line ending issue on this file. @thecoolestguy since you are oiur in house resident expert on line endings, you wanna take point on fixing and merging this one?

**Comment by jrjohnson** [comment]
@jenzweben can you add these colors to components/_variables.scss and then reference them by name in this _global.scss file?

Then we can find them elsewhere if necessary.

$published_color:
$schedule_color:

**Comment by jenzweben** [comment]
sure

**Comment by jrjohnson** [comment]
Looks like you will have to to a git pull --rebase upstream master and fix conflicts.
Probably because I messed with global as well today.
It wont merge otherwise.  Let me know if you want an assist.

**Comment by jenzweben** [comment]
fixed files - this is ready to go

**Comment by jrjohnson** [comment]
@saschaben - please confirm these colors are correct and then this is ready to merge.

**Comment by saschaben** [comment]
"scheduled" is displaying the "Published" label. Correct color, wrong label.

**Pull request merged**
