### PR TITLE
Update Simple Charts to v12.0.0

### PR DESCRIPTION
**Pull request by jrjohnson**
This is our newly released v2 addon version of simple charts. The tooltip styles were fixed in this version so we can get rid of some of our customizations.

Needs click testing most of all.

### CODE REVIEW

**Comment by michaelchadwick** [comment]
@jrjohnson Ooo, I wanna test this! After pulling the PR, how can I best test it?

**Comment by jrjohnson** [comment]
Discussed at standup, but adding here as well: Test points are any charts, lots of which are accessible from the overview of a course.

**Review by stopfstedt — DISMISSED** [review]
click tested, LGTM.

**Review by stopfstedt — DISMISSED** [review]
LGTM

**Review by dartajax — APPROVED** [review]
click tested - seems fine to me

**Pull request merged**
