### PR TITLE
Add offering details to sessions list

### LINKED ISSUE #226: Session offering / group details in the list
When a use clicks the offering count in a session list the table row should expand to list those offerings.  Much like the course delete confirmation works.

@jenzweben - please mock this up.

### PR DESCRIPTION
**Pull request by jrjohnson**
By clicking on the offering count for a session all of the times are
shown.

Fixes #226

### CODE REVIEW

**Comment by saschaben** [comment]
Whew! this is awesome stuff. Having played a bit, though, I am reconsidering my "no eye" comment earlier. I think we definitely need some identifier here for the users. Let's go ahead and put in the eye (even better if we can have the eye flip to a fa-chevron-down or similar when the view is open?), and see how it looks in real use, and discuss on thursday with @jenzweben.

**Comment by jrjohnson** [comment]
@saschaben - as requested an eye and a down arrow.  How's that?

**Comment by saschaben** [comment]
@jrjohnson definitely provides more user context....

but all those eyes still kinda creep me out. Good enough for gov'mint work.

**Comment by thecoolestguy** [comment]
IE 11 fail only - merging!

**Pull request merged**
