### PR TITLE
Update ember-cp-validations to v3

### LINKED ISSUE #2041: Update our validation library
We need to update to the latest v3 stuff.

https://github.com/offirgolan/ember-cp-validations/blob/master/UPGRADING.md

### PR DESCRIPTION
**Pull request by jrjohnson**
This update uses CPs instead of private functions to define properties
for validations.  This necessitated changing some of our validations to
match.

Fixes #2041

Needs: 
- [x] Tests to pass
- [x] Click test of some untested validations

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 6167da040f0d593c0b81354429dfda8f8cd6f7bc

http://deploy-preview-2140.ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
@dartajax please test existing validations to ensure I didn't mess up any of them.

**Comment by dartajax** [comment]
It looks good to me.

**Comment by stopfstedt** [comment]
reviewed and in larger parts click-tested. LGTM. :+1:

**Pull request merged**
