### PR TITLE
Refactor Styles

### PR DESCRIPTION
**Pull request by jrjohnson**
Sass modules are the preferred way to link our mixins and variables together in new versions of sass. This is the least amount of change I could make work while still making an attempt to align with this new paradigm.

Requires ilios/common#3239

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax this needs a click around style review for anything that looks weird, it's hopefully all working.

**Comment by dartajax** [comment]
It looks even weirder in non-expanded mode - that's where I noticed it first ...

image

**Comment by dartajax** [comment]
same is true with objectives ...

image

**Comment by jrjohnson** [comment]
Style issues are fixed in https://github.com/ilios/common/pull/3267 I think we can probably move ahead with merging this and get those out with the next common update, which can be done pre-release of this change.

**Review by stopfstedt — APPROVED** [review]

**Pull request merged**
