### PR TITLE
Improve big list styles

### LINKED ISSUE #1791: Cleanup main list styles
Style refactor and consolidation for courses, learnerGroups, instructorGroups, schools, programs lists.

### PR DESCRIPTION
**Pull request by jrjohnson**
Using mixins instead of inheritance to make the big lists easier to
understand and style in the future.

Fixes #1791

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben / @dartajax please check that I didn't mess up the styling of the courses, learner groups, instructor groups, schools, or programs lists.

**Comment by saschaben** [comment]
In order to avoid losing the far right of the site container for list pages when collapsed to mobile size, we need to add a `margin-right: 5px` to the `#site-container` value in css:

margin-right

Otherwise, this is superduper rocknroll. The above if needed may be added as a follow-on ticket, as it does not impact usage. It's just not as perfectly pretty as it should be.

**Comment by saschaben** [comment]
👍

**Comment by stopfstedt** [comment]
nice and clean. LGTM.

**Pull request merged**
