### PR TITLE
re-positioned close button on search form.

### LINKED ISSUE #330: Add (New) Session (or edit) >> MeSH vs. Directors >> Black "x" appears in Different Location
see the screen shots below ...

blackxdirectors
blackxmesh

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #330

### CODE REVIEW

**Comment by jrjohnson** [comment]
This ends up with a double close button on chrome.  I think we should just remove the .close button and let people use the backspace key.  Then as browsers increase support for the 'search' type input the display will look good for them.  Alternatively remove the type='search' from the user search box.  So chrome doesn't get punished for doing thing right.

**Comment by saschaben** [comment]
I think I agree with @jrjohnson --- let's remove the .close button and see how the users respond to it. If we need to we can flip this pretty easily, and re-add the .close button and remove the type="search" instead, until the other browsers catch up.

**Comment by stopfstedt** [comment]
on it. thanks!

**Comment by jrjohnson** [comment]
@dartajax you can test this at http://5644db9f71e20a2b60000025.ilios-frontend.netlify.com/  ensure that the director search and mesh search still work for a course.

**Comment by dartajax** [comment]
I will test that right now.  Thanks for nelifying it.

**Comment by dartajax** [comment]
:+1:

**Comment by dartajax** [comment]
Although I found something else to report in a new issue.

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
