### PR TITLE
Edit user biographical information

### LINKED ISSUE #1549: Edit individual user profile data
Need to be able to edit:
- [x] Name
- [x] Campus ID
- [x] Email
- [x] Phone

Refs #684

### PR DESCRIPTION
**Pull request by jrjohnson**
Clicking the pencil icon by the user name will open an edit form where name and other biographical information can be changed.

This was mainly a result of trying to figure out a way to edit the name in place since it is actually three values (first, middle, last) but only displays as a single value on the page.

Fixes #1549

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben - check this out and let me know what you think.  Instead of individual edit in place components I built all of the biographic information into a single form.

**Comment by saschaben** [comment]
looks great. Let's get some validation in there and I think we are fine for a first round.

**Comment by jrjohnson** [comment]
Whoops - validation is in.  Just forgot to actually validate anything.  👎

**Comment by saschaben** [comment]
:+1: 
w00t!

**Comment by stopfstedt** [comment]
LGTM

**Pull request merged**
