### PR TITLE
Improved Learning Material Managment

### PR DESCRIPTION
**Pull request by jrjohnson**
Converted into our new table pattern and refactored out some of the old
patterns.

- [x] convert LM list into a more modern component
- [x] improve the manager so it is clearer that you have to save (by gettign rid of editable components and just having them display as form items
- [x] either pass the LM itself down or pass the changed fields up to make the manager less werid
- [x]  Update common to bring in all translations and new models

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit ac3bcc904fe6b1d9e2639956f14ed9311eb5d131

https://deploy-preview-3235--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
One thing I noticed is that editable fields remain "open".

image

**Comment by dartajax** [comment]
LGTM 👍 

My previous deleted comment is the intended behavior and I approve.

**Comment by jrjohnson** [comment]
@stopfstedt this is ready for review again.

**Pull request merged**
