### PR TITLE
Allow new learner groups to be created full

### LINKED ISSUE #1591: allow learner groups to be populated on creation -- or not.
For top level groups, they should allow for creation either as empty groups, OR with selected cohort members.

For sub groups, should allow for creation either as empty groups, OR with selected group tree members.

### PR DESCRIPTION
**Pull request by jrjohnson**
Allows the entire cohort to be placed into a new group instead of just
creating them empty.

Fixes #1591

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben can you give this a look?

**Comment by saschaben** [comment]
this looks good. we'll still at some point have to address the same functionality at the sub-group level, but that gets into splitting / randomization stuff, and so is really a different ticket for another day.
👍

**Comment by saschaben** [comment]
one thing: can we get the action spinner on the `Done` button when the transaction is fired?

**Comment by jrjohnson** [comment]
Spinner added, tests passing, ready for review.

**Comment by stopfstedt** [comment]
I approve of this.

**Pull request merged**
