### PR TITLE
Re-write user menu to meet accessiblity guidelines

### PR DESCRIPTION
**Pull request by jrjohnson**
Accounts for keyboard navigation and screen reader users.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 417da8150db06b4decaa8694d5b2ce81776ef752

https://deploy-preview-3902--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
@saschaben in order to meet color contrast guidelines I needed to put the menus into a box, it turns out nothing works against our orange. Please give this a look and let me know what you think.

**Comment by saschaben** [comment]
if we need to use black for the font in these two menus, we should probably modify the icons to match:



Also -- is it possible to reverse the colors for onMouseOver, so that white is the hover and grey is the default? That might make it a bit less glaring in the layout when unselected.

are there any other areas affected by this PR?

**Comment by saschaben** [comment]
current rendition appears to have lost the `border-radius` setting on the menus....

**Comment by jrjohnson** [comment]
Good catch @saschaben - borders are hard! Fixed now.

**Comment by saschaben** [comment]
:+1:

**Pull request merged**
