### PR TITLE
Learning materials styled

### PR DESCRIPTION
**Pull request by thecoolestguy**
Needs acceptance tests and working file upload, refs #396

### CODE REVIEW

**Comment by saschaben** [comment]
looks soooooo much better!

need to make tickets for (if we haven't already);

 - adding LM file search to the Add file form;
 - adding dependency of state to actions for copyright (checkbox not checked = grey text, rationale box, inactive save; checkbox checked = black text, no rationale box, active save; checkbox not checked but rationale entered = grey text, active save)

**Comment by thecoolestguy** [comment]
looks like the form is not displaying the default dropdown values

**Comment by saschaben** [comment]
OK. So dropdown defaults are displaying for me, but form is not saving changes to status or user role properly -- they revert to defaults when pulling up secondary "attach to the course" form. API issues combined with the two-step form here may be at fault...?

**Comment by jrjohnson** [comment]
scss-lint is failing.

**Pull request merged**
