### PR TITLE
Scope reports by school

### LINKED ISSUE #1138: Scope MyReports by school
The plan:
1) Add a schoolId to the reports table (https://github.com/ilios/ilios/pull/1181)
2) Add For:  [School] Dropdown to report creation

If school is left blank the existing bad behavior will be what happens.  If a school is selected then:
1) The Object select list should be scoped to that school
2) When the report is saved the school name should be in the default title:
`All Courses in Medicine` or `All Courses in All Schools`

@saschaben and @dartajax can you please translate:
'All Schools'
and 'For' and in For [ DROP DOWN WITH SCHOOL NAMES ]

### LINKED ISSUE #1214: My Reports: don't send school when filtering MeSH Terms.
as discussed. 

refs ilios/ilios#1183.

### LINKED ISSUE #1219: My Reports: don't send school when filtering learning materials.
another one that cannot be scoped by school.

refs ilios/ilios#1183

### PR DESCRIPTION
**Pull request by jrjohnson**
Add a school selector to the reports builder.  When a school is picked then:
- only display objects related to the school to be selected
- Limit report results by that school
- Show the school name in the default report title

Fixes #1138 
Fixes #1214
Fixes #1219

Work in progress: This needs ilios/ilios#1180 and ilios/ilios#1183 to be fixed before it will work and can be tested.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Needs to switch from sending `school` to sending `schools` as it is in https://github.com/ilios/ilios/pull/1187

**Comment by jrjohnson** [comment]
@saschaben this can now be reviewed against demo.

**Comment by jrjohnson** [comment]
Issue:
1. Create a new report
2. Choose Course associated with Topic
3. Change subject to session

DIE DIE DIE!

**Comment by jrjohnson** [comment]
@saschaben problem with changing values back and forth should be fixed. please review again.

**Comment by saschaben** [comment]
:+1:

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
