### PR TITLE
Manage Vocabularies

### PR DESCRIPTION
**Pull request by jrjohnson**
Adds the vocabulary manager to the school manager.  Allows for creating vocabularies, editing titles, adding and deleting terms and changing term descriptions.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Damn - turns out old and new validation libraries can't run next to each other.  I'm going to have to re-work all of our existing validations.   I think that will need to be a different PR, its kind of a big job.

**Comment by jrjohnson** [comment]
@saschaben this is ready for review. All that is left is to fix a few remaining tests and add translations which should not affect the functionality.

**Comment by saschaben** [comment]
not sure if you intended for me to be reviewing at this point, or whether my assignement was just hanging about while you worked on tests and validations, but this is still throwing errors whenever an attempt is made to access an existing vocab (`vocabulary.get(...).then is not a function`).

**Comment by saschaben** [comment]
..and since you are clearly still working, reassigning to you!

**Comment by jrjohnson** [comment]
Good catch.  Thanks.  I will take a look.

**Comment by jrjohnson** [comment]
@saschaben - this is ready for review again.

**Comment by saschaben** [comment]
Looking good. A couple of things to clarify usability, all presentation, none functional -- if they are bigger than a breadbox to complete, we can deal with it in another update, but...

1: differentiate the term display text from the descriptive notes display text: either make the term itself _bold_, or reduce the size of the descriptive note font, or prefix notes (once added) with the label "Descriptive notes:", or a combination of those.

2: "click to add descriptive notes" should be italicized (this is actually a style change that should be applied globally).

3: once we've clicked down into terms (eg, "All Vocabularies | UCSF 49 | Common Cancers"), add a label above the list box: "Sub-items" 

managevocabs

**Comment by jrjohnson** [comment]
@saschaben changes made.  Take a look.

**Comment by saschaben** [comment]
Looks good. Is there any chance of getting the in-place edit text style for the terms to be bold? It would really help. Otherwise, this looks good to go.

**Comment by jrjohnson** [comment]
@saschaben ready for review again.

**Comment by saschaben** [comment]
:+1:  Superbe.

**Comment by jrjohnson** [comment]
@stopfstedt I apologize for the big merge.  Got a little bit out of hand.

**Comment by stopfstedt** [comment]
:+1: LGTM

**Pull request merged**
