### PR TITLE
chore(package): update ember-cli-string-helpers to version 1.1.1

### PR DESCRIPTION
**Pull request by jrjohnson**
Closes #2829

https://greenkeeper.io/

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit eda142a87d522d27770f600ebaa8f7902db698f0

https://deploy-preview-2830--ilios-frontend.netlify.com

**Comment by gabycampagna** [comment]
Jon, I can approve this PR and merge if it is ok with you.

**Comment by saschaben** [comment]
@gabycampagna I don't see any issues here but there may be upstream dependencies needing a wait on this -- I've no idea. @stopfstedt or @jrjohnson should give a word in, but I don't know if they will be around anytime soon if you are wanting this to merge for your work....

**Comment by gabycampagna** [comment]
@saschaben I don't need this for my work. Just thought I should try to help out. I will hold off on merging.

**Pull request merged**
