### PR TITLE
list parents, competencies and MeSH terms with objectives in course print view.

### LINKED ISSUE #3932: course print view: show parent objectives in objectives list
this should help in identifying which course- and session-objectives are wired up correctly. it's easy to spot in the course manager proper, but not in the print view.

possibly to run the connected higher level objectives in parenthesis _after_ the actual objective (similar to running  competencies in the event details).

to be further discussed, should be fairly straightforward to implement.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #3932 

course objectives table:

selection_079

session objectives table:

selection_080

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 65ea349b1d22bbe4d251e63ff76bbe813c24c9a6

https://deploy-preview-3947--ilios-frontend.netlify.com

**Comment by stopfstedt** [comment]
@dartajax please click review. thanks!

**Comment by dartajax** [comment]
Can we get rid of the bullet point in Print Preview so that it matches the Courses and Sessions view?

image

image

**Comment by dartajax** [comment]
Looks good otherwise.

**Comment by stopfstedt** [comment]
@dartajax good suggestion, but print-styles should/will be addressed as a separate issue. so, no - not now.

**Pull request merged**
