### PR TITLE
Improve Mobile Experience

### PR DESCRIPTION
**Pull request by jrjohnson**
This adds metadata and icons to allow Ilios to be 'installed' on mobile devices.

The icons are automatically generated from ilios-sunburst.svg so we don't have to keep track of them ourselves.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 13c157ed54f4c86a9aab1a53d212e73ec9e3bbbf

https://deploy-preview-3365--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
This is seriously cool.

**Comment by jrjohnson** [comment]
I've marked it as WIP because the icon iOS uses ends up with a black background. I'm trying to figure out why.

**Comment by jrjohnson** [comment]
Group feedback:
All icons on all devices should have a white background.

**Pull request merged**
