### PR TITLE
Refactor Learner Groups List

### PR DESCRIPTION
**Pull request by jrjohnson**
Octanification plus consolidation of controller into a top level
component with only query params at the controller level.

### CODE REVIEW

**Review by dartajax — CHANGES_REQUESTED** [review]
This is on demo3 ...

image

This is on netlify of this PR ...

image

**Review by stopfstedt — CHANGES_REQUESTED** [review]
found a regression - sorting the learner groups is no longer "sticky", `sortBy` does not get set in the URL anymore.

**Comment by jrjohnson** [comment]
Solid reviews, two excellent catches!

> This is on netlify of this PR ...
I fixed this centering issue and it should look better now.


> found a regression - sorting the learner groups is no longer "sticky", `sortBy` does not get set in the URL anymore.
I removed this behavior because I didn't think persisting sort order to the URL had user value since, but I'm 100% willing to be talked back into it, I just couldn't come up with a reason to keep it.

**Comment by stopfstedt** [comment]
> I removed this behavior because I didn't think persisting sort order to the URL had user value, but I'm 100% willing to be talked back into it, I just couldn't come up with a reason to keep it.

I'm good either way on this.

**Review by dartajax — APPROVED** [review]

**Comment by dartajax** [comment]
The issue I reported has been resolved.

**Review by stopfstedt — APPROVED** [review]

**Pull request merged**
