### PR TITLE
couple inplace-html fixes (froala issues)

### LINKED ISSUE #900: Enter New Objective Using The Froala Box - Bullets and Numbered Lists Don't Appear Until Saved
Using ...

http://5621441ed6865d355b00025f.zoo-keeper-levels-51188.netlify.com/dashboard

... to test the Froala text editor I encountered the following scenario ...

froala1

As shown above, click to add an objective ...
As shown below, select the numbered lists option in the editor ...

froala2

froala3

Process the save event by clicking the Done button.

froala4

### LINKED ISSUE #904: Froala Button Change To Done / Cancel on Session Description
We might as well standardize on Done / Cancel with the text editor Froala control. See screen shot.

donecancel

### LINKED ISSUE #945: Froala Text Fields Don't Line Up Very Well After Save (Alignment Issue?)
See the screen shots below ...

This is in Learning Materials.

notes1

Save the LM.

Retrieve the LM.

Review the alignment.

notes2

The same is true with Instructional Notes (another Froala field). See below ...

notes3

Save the record and review the alignment misery.

notes4

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #904 
Fixes #945 

Try to fix #900. This one seems like an addon issue.

### CODE REVIEW

**Comment by saschaben** [comment]
looks great from a user-functional POV.

**Comment by jrjohnson** [comment]
@homu r+

**Comment by jrjohnson** [comment]
:+1: via @saschaben 
@homu retry

**Comment by jrjohnson** [comment]
@homu retry

**Pull request merged**
