### PR TITLE
Improved Styling of Program Year Competency manager

### LINKED ISSUE #522: fix styling of program year - competencies container
the top border of the box is missing where selected competencies are displayed.

ilios 2015-05-07 13-36-54

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #522

### CODE REVIEW

**Comment by saschaben** [comment]
any chance we can make bold the top level values as well?

**Comment by jrjohnson** [comment]
@saschaben - hows that?

**Comment by saschaben** [comment]
Will take a look this evening. Let's do code review now, and if it passes and I am down with the update, I'll merge as well.

**Comment by saschaben** [comment]
looks great.

**Pull request merged**
