### PR TITLE
fixes various minor issues with course viz

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes https://github.com/ilios/ilios/issues/5816
fixes https://github.com/ilios/ilios/issues/5817

### CODE REVIEW

**Comment by michaelchadwick** [comment]
@stopfstedt Two things I noticed while reviewing this:
1. Why show any visualization type to click on if clicking into each shows nothing? https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276
2. Why show a filter box if there's nothing to filter? https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276/session-types and https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276/instructors

**Comment by stopfstedt** [comment]
> @stopfstedt Two things I noticed while reviewing this:
> 
>     1. Why show any visualization type to click on if clicking into each shows nothing? https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276

what would you show instead here?

> 
>     2. Why show a filter box if there's nothing to filter? https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276/session-types and https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276/instructors

yep, it's annoying and shouldn't be there.fixing that would require relocating the data loading process further up in the component hierarchy, or moving the filter input further down.

**Comment by michaelchadwick** [comment]
> >```
> > 1. Why show any visualization type to click on if clicking into each shows nothing? https://deploy-preview-8224--ilios-frontend.netlify.app/data/courses/2276
> > ```
> 
> what would you show instead here?
> 
Maybe just show a "There are no visualizations to show because there is no course data yet." kind of statement?

**Review by dartajax — APPROVED** [review]
looks good to me

**Pull request merged**
