### PR TITLE
Limit deletes in the courses area

### LINKED ISSUE #1182: Delete Permission Review
I think we're currently allowing delete option to anyone and that should change.  @saschaben can you review who should be able to delete a course, session, or offering?  Any instructor currently has access to those options.

### PR DESCRIPTION
**Pull request by jrjohnson**
Removed the delete icon for courses, sessions, and offerings when the user is not a Developer or a director in the course, or an instructor in the offering.

Fixes #1182

### CODE REVIEW

**Comment by saschaben** [comment]
FYI, our ancient permissions matrix: https://www.dropbox.com/s/7cerjnm5qbfion5/permissions%20matrix%20-%20app.%20B.docx?dl=0

**Comment by saschaben** [comment]
we should probably apply this logic to course level objectives as well...we will map out the specific permissions to course level / session level internal attributes for associated users in another ticket.

**Comment by saschaben** [comment]
seems to work as advertised.
:+1:

**Comment by stopfstedt** [comment]
:+1:

**Comment by stopfstedt** [comment]
@homu r+

**Pull request merged**
