### PR TITLE
Assign students to a primary cohort

### LINKED ISSUE #1546: Add ability to assign new students to primary cohort
When new students are ingested they do not have a primary cohort.  In v2 we exposed a list of these students to administrators for assignment which we need to do again.

UI: Should looks very much like the multi-edit controller for learner groups which allows for the selection of many students and then a dropdown indicating the cohort to assign them to.

Refs #684

### PR DESCRIPTION
**Pull request by jrjohnson**
Looks up all students in a school that do not have a primary cohort and
allows them to be assigned to one.

Fixes #1546

### CODE REVIEW

**Comment by saschaben** [comment]
very nice indeed. finishing touches:

1: checkbox should be moved to the left to provide space between link to user edit and checkbox activation clicks;
2: success message needed after transaction: " _n_ users successfully added to the cohort [Cohort Name]"

**Comment by saschaben** [comment]
once assigned, student records are not dropping off the list of users to be assigned. hard refresh of page will update the list.

**Comment by saschaben** [comment]
good enough for guvmint work. Let's roll with this as a first pass.

**Comment by stopfstedt** [comment]
reviewed, LGTM.

**Pull request merged**
