### PR TITLE
Fix Broken Courses List Filter

### LINKED ISSUE #336: filter/search on course list page no longer working
looks like we lost this in the last batch of merges.

### PR DESCRIPTION
**Pull request by jrjohnson**
The filter was relying on the wrong property.  I also cleaned up the
logic and added tests.

Fixes #336

### CODE REVIEW

**Comment by saschaben** [comment]
seems to be all fixed up now.

**Comment by jenzweben** [comment]
still broken for me...

**Comment by jrjohnson** [comment]
YAY for automated tests, caught a logic problem in my first try.  I fixed it and tests should now pass.  @thecoolestguy you will have to star again.

**Comment by saschaben** [comment]
all fixered

**Pull request merged**
