### PR TITLE
added text-wrap mixin so it fixes long URLs in Session->ILMs

### PR DESCRIPTION
**Pull request by michaelchadwick**
Refs ilios/ilios#4308

### CODE REVIEW

**Review by jrjohnson — CHANGES_REQUESTED** [review]
Nice! The tests aren't running right now, but this would still be a perfect things to add some Percy screen shots for. Can you throw a `percySnapshot()` into a test where this issue can be shown?

**Review by stopfstedt — APPROVED** [review]

**Comment by michaelchadwick** [comment]
@jrjohnson Whenever I run tests locally, I get the following error per Percy: 
Screenshot 2024-07-08 at 1 35 04 PM

I have not used Percy either, so what're the steps to fixing this and adding such a thing to a test?

**Comment by jrjohnson** [comment]
They'll never run locally, but in any test you can use the `await percySnapshot(assert);` to take a screen shot and add it to our library of shots so it will be compared in the future. Once you push to GitHub then the magic will happen.

**Comment by michaelchadwick** [comment]
@jrjohnson Changed one of the titles of the LMs so that it was a long URL like in the issue. There was already a percy screenshot taken of that test, so now it should show up there?

**Review by jrjohnson — APPROVED** [review]

**Comment by jrjohnson** [comment]
Done, handed off to @dartajax for final review and merge.

**Comment by dartajax** [comment]
I tested this - looks great - `gonna merge now`

**Pull request merged**
