### PR TITLE
Fixed course and session publish

### LINKED ISSUE #202: Publish buttons on course and session displaying at the same time is confusing
@jenzweben please see it there is something we can do about this.
screen shot 2015-02-26 at 11 46 41 am

### PR DESCRIPTION
**Pull request by jrjohnson**
Added session publication workflow steps
Improve style for publish/unpublish buttons to differentiate them from each other.  Fixes #202
Button name now has full 'Publish Course' 'Publish Session' text

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/280" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
Much better. For now. I'm not loving the different font sizes next to each other in the buttons though; we will need to do something about that. Perhaps reduce the font size in the .action-menu .button to 0.85em to match the unpublish, and increase padding to "0.55em 1.5em 0.55em 0.5em"....?

Uncertain of best approach (changes here impact visual issues elsewhere). Let's discuss in meeting before determining if this needs a new styling ticket.

**Comment by thecoolestguy** [comment]
merge conflicts needs rebase.

**Comment by jrjohnson** [comment]
@thecoolestguy - rebase and ready to merge.

**Comment by thecoolestguy** [comment]
Ninja-starred for code... Merge when functionality confirmed!

**Pull request merged**
