### PR TITLE
fixed regression with dashboard calendar school switcher.

### LINKED ISSUE #2647: Regression Bug -- School Switcher Missing -- Calendar >> All Events
When All Events is selected, users with permissions in more than one school should be able to access the school selector to load the full calendar of any other school to which the have permissions. 

This still works properly on stage3, which may have an older code base.

See below -- I am logged in and am in all six schools - full permission.

image

Here I am on prod - same permissions.

No school selector.

image

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2647

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 23f9d7ad55cbd4acc0545ae11e5dc1c6902dfeb7

https://deploy-preview-2648--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
LGTM :+1:

**Comment by stopfstedt** [comment]
@jrjohnson good call, i'll put some test(s) in.

**Comment by dartajax** [comment]
It looks good to me as well.

**Pull request merged**
