### PR TITLE
save offering/user(s) association on the offering side.

### LINKED ISSUE #1080: Add New Offering With Instructor Fails
It could be re-writing to the User end point incorrectly or when it shouldn't be.

Steps below ...

image

image

image

image

image

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1080.

### CODE REVIEW

**Comment by stopfstedt** [comment]
@jrjohnson ok, this fixes the imminent issue of saving offering relationships from the wrong end.
however, this introduces a regression with the assignment of default instructors, default instructor-groups to offerings via small groups generator. they do not stick anymore. i've been unable to link these to the offering by chaining promises _before_ the offerings are created. still, better than before. any pointers are welcome. thanks!

**Comment by jrjohnson** [comment]
:+1:  via Sascha
@homu r+

**Comment by stopfstedt** [comment]
rebased against master.

**Comment by jrjohnson** [comment]
:+1: group choice to move ahead with this as it solved many issues.  @stopfstedt should document remaining problems in a new ticket.

**Comment by jrjohnson** [comment]
@homu retry

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
