### PR TITLE
ember watson:convert-ember-data-model-lookups

### PR DESCRIPTION
**Pull request by djvoa12**
This changes the way model lookups happen when working with Ember Data. When using `hasMany` or `belongsTo`, the first argument will become a dasherized string.

### CODE REVIEW

**Comment by djvoa12** [comment]
@jrjohnson ready

**Comment by jrjohnson** [comment]
@djvoa12 This seems to be all white space changes?  Is that correct?

**Comment by djvoa12** [comment]
@jrjohnson I think so I just wanted to merge all changes that resulted from all the commands so it won't be caught again for some update in the future, if any.

**Comment by jrjohnson** [comment]
:+1:

**Pull request merged**
