### PR TITLE
switched offering buttons

### LINKED ISSUE #1019: Flip Small Groups / Offerings Buttons and Make Small Groups the Default
Current situation shown below -- this is when adding Offerings / Events to a Session.

The default is shown by the squiggly arrow.  We need to switch the buttons and make Small Groups the default rather than Offering and have Small Groups on the left side and Offering (un-selected by default) on the right side.

offeringdefault

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #1019

### CODE REVIEW

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
code review :+1: just waiting on tests

**Comment by jrjohnson** [comment]
@djvoa12 tests are actually failing here.  Can you take a look?

**Comment by saschaben** [comment]
:+1:

**Pull request merged**
