### PR TITLE
make program objectives without competencies selectable as parents.

### LINKED ISSUE #1905: Cannot add parent objective to course objective if the parent program objective is not mapped to a competency
see also #1696.

A program competency should be available for selection as a parent regardless of whether it has been mapped or not to a higher level parent. 

Mapping from one level to the next higher level cannot be dependent on the mapping of other levels.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1905

### CODE REVIEW

**Comment by stopfstedt** [comment]
@saschaben please review and let me know if this hits the mark. thanks!

**Comment by saschaben** [comment]
This should work just fine. The "no domain" category works for me.

**Comment by stopfstedt** [comment]
ok, thanks. will complete translations and add tests.

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
