### PR TITLE
added special attire/equipment indicators to event details.

### LINKED ISSUE #2118: Special Equipment and/or Attire Indicators Missing From Detail Page
Currently, there is no way to tell (as a Student) if Special Equipment is needed and/or is Special Attire is needed.  There used to be an icon on the Calendar and a written indication on the Detail Screen.  See several screen shots below for example.

image

image

image

Nothing available for Special Equipment or Attire available on mouse-over either.

With other details removed, the Detail Screen only indicates as shown below that this Session is a Laboratory.  It doesn't advise here either about whether special Attire or Equipment are needed.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2118 

selection_005

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 9aa5b56652d4558fcdd6009c8240cc35f2e2ab85

http://deploy-preview-2173.ilios-frontend.netlify.com

**Comment by saschaben** [comment]
love the necktie

**Comment by jrjohnson** [comment]
@stopfstedt I just released calendar version 6.0 with the required changes.

**Comment by jrjohnson** [comment]
@stopfstedt I only see changes to the single even view.  #2118 requires changes to the calendar weekly and daily blocks as well.  Should I make that a new issue and merge this as a partial fix?

**Pull request merged**
