### PR TITLE
tinkering with fractal page objects

### PR DESCRIPTION
**Pull request by stopfstedt**
throwaway code - i'm just trying this out as a potential replacement for  ember-cli-page-objects.

### CODE REVIEW

**Comment by jrjohnson** [comment]
I'm a big fan of this library and the simplification removes a lot of the things we don't use in our existing page object library. Long term it's much more maintainable and, IIRC, one of the drivers for it is that the author was putting a lot of effort into ember-cli-page-object that felt wasted. It's a clearly a pretty big lift to make the change though. We could possible code mod a chunk of this, but I'm guessing a pretty significant amount of manual work will be required too.

**Comment by stopfstedt** [comment]
> The `fractal-page-objects` addon seems quite similar in syntax and usage to `ember-cli-page-objects`. Do the more advanced uses, like using the `text()` or `clickable()`, work the same?

it's all rather bare bones - the helpers have to come `qunit-dom` since fractal doesn't provide any.

**Comment by stopfstedt** [comment]
also, something isn't right with fractal in ilios tests. 

consider this, for example:

`assert.dom(component.firstButton.element).hasNoClass('active');`

the `.element` shouldn't be part of that invocation, according to [the docs](https://github.com/bendemboski/fractal-page-object?tab=readme-ov-file#integrating-with-qunit-dom-and-embertest-helpers), this should be possible.

`assert.dom(component.firstButton).hasNoClass('active');`

however, this throws a test-breaking error.


i tried fractal out in a vanilla ember app, and `.element` was not necessary there. 

to be further explored.

**Comment by jrjohnson** [comment]
The element dom descriptors RFC is fairly new. Maybe we have an old version of something?

**Comment by stopfstedt** [comment]
i'm tabling this, hopefully forever.

**Pull request closed without merging**
