### PR TITLE
added clear filters

### LINKED ISSUE #858: Clear All (for Filters) Needed on Dashboard
When filters have been activated and selected, there should be link or button of some sort to remove the filters completely and show everything.

Ugly mock of the strip (buttons adjusted as well) below ....\

newstrip2

### PR DESCRIPTION
**Pull request by djvoa12**
Ready for review and merge when approved.

Note: My editor removed lots of spaces that shouldn't be there.

Fixes #858

### CODE REVIEW

**Comment by saschaben** [comment]
sweet.

**Comment by jrjohnson** [comment]
I would rather see this as a list of applied filters with an x to clear them all at the end.  This seems to be a pretty common pattern for this type of thing.

**Comment by saschaben** [comment]
@jrjohnson that is the existing 2.4.8 pattern --- definitely would be preferable, but requires some UI thought regarding the display of the filter list. This as is could be an interim solution while we hash out the display question. That filter list can get really long. In the current 2.4.8 iteration it wound up a less than ideal compromise between available space, legibility, and code constraint. Would love to find a better answer this time....

**Comment by djvoa12** [comment]
That's another PR I am going to create to fixes issue #860.

**Comment by jrjohnson** [comment]
:+1:

**Pull request merged**
