### PR TITLE
fixed drop-down for multi-edit

### LINKED ISSUE #1237: Non-Functional Drop Down Menu in Learner Groups when List is Too Long
image

I want to move one of the students in "ABG Small Group 1" into the sub-group "ABG Small Group 1 >> Ajax 1".

image

Using the unwieldy drop-down shown below (this is in Mult-edit mode), I am trying to select where the squiggly arrow is indicating.  Nothing happens when that item is selected.  There is no functionality present to move learners to the sub-group of the sub-group in multi-edit mode.

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #1237 

screen shot 2015-12-10 at 3 20 50 pm

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax this can be reviewed with a branch against demo.

**Comment by dartajax** [comment]
I will try that right now.

**Comment by dartajax** [comment]
I tried git fetch djvoa12 and received an error that either the repository doesn't exist (and I beg to differ) or there may be some access rights issues - could that be the case?

image

**Comment by dartajax** [comment]
:+1:

**Comment by dartajax** [comment]
It looks much better.

**Pull request merged**
