### PR TITLE
Change learner group subgroup member title based on context

### LINKED ISSUE #647: mislabeled section in learner group display
group1

This label needs to be context-driven. If viewing a top level group, we should refer to group (or "this level"). If viewing a sub-group (non-top level), it should refer to sub-group (or small group, or "this level").

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #647

### CODE REVIEW

**Comment by saschaben** [comment]
copying note from #647:

I just had a brainstorm: this label is better but still not really accurate from the POV of a user. If I navigate to Anatomy Lab, I should see that there are 26 sub-groups that contain all the learners (and ideally no one just floating in the top level group). But all those learners are "in" Anatomy Lab prime, since all their respective sub-groups are "in" Anatomy Lab prime. So rather than saying "Anatomy Lab Members NOT in this Group" at the top level (and we are ONLY talking here about top level), which is wrong on a number of levels -- members can't be non-members, and they are all in the group as noted above --why don't we say "Anatomy Lab Subgroup Assignments"? That's not only more accurate, but actually describes what we are really showing in that section....thoughts?

**Comment by saschaben** [comment]
...or "[Top Level Group Name] Learner Assignments"...?

**Comment by jrjohnson** [comment]
I can do either of this in a matter of seconds.  My vote is Anatomy Lab Learner Assignments.  Or even Anatomy Lab Learner Subgroup Assignments.

**Comment by saschaben** [comment]
Learner Assignments it is. users always hated "subgroup". less of that is better.

**Comment by saschaben** [comment]
Mergie strikes!

**Pull request merged**
