### PR TITLE
Make session filter name a query parameter

### LINKED ISSUE #1675: Filters Need to Maintain State on the Session List
It is nice that the sort order remains but the filtering does not.

Filter for exams and select one to review as shown below...

image

Return to the session list as shown below 

image

Now the screen reverts and loses the filter was applied.

image

This is a good one to fix as far as user experience is concerned.  I have heard about this frequently from users.

### PR DESCRIPTION
**Pull request by jrjohnson**
This results in the filter being sticky while navigating between
sessions.

Fixes #1675

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please review and make sure this meets muster for #1675

**Comment by dartajax** [comment]
Unless I did something wrong, which is definitely possible, I am not seeing the session filters remaining as search parameters.  The session list resets.

**Comment by dartajax** [comment]
I am passing this on to @stopfstedt for code review.  Functionally, it seems fine to me.

**Comment by stopfstedt** [comment]
click tested and code reviewed. :+1:

**Pull request merged**
