### PR TITLE
Better more informative report results

### LINKED ISSUE #1184: Extend and Format MyReports output
current output for myReports is unformatted and incomplete. We need to:

A) provide more information in the output.
- [x] COURSE should display course name + year
- [x] SESSION should display owning course name + year
- [x] PROGRAM should display owning school
- [x] PROGRAM YEARS should display owning program + school

Context is everything.

B) for permitted users, the output should be hyperlinked to the admin view of that item for:
- [x] COURSE
- [x] SESSION
- [x] PROGRAM 
- [x] PROGRAM YEAR

### PR DESCRIPTION
**Pull request by jrjohnson**
Output for courses, sessions, programs, and program years has more details and a link to the edit route for that item.

Fixes #1184

### CODE REVIEW

**Comment by saschaben** [comment]
any report output return the following errors:
```
_this[mapper] is not a function

TypeError: _this[mapper] is not a function
    at http://localhost:4200/assets/ilios.js:35802:22
    at tryCatch (http://localhost:4200/assets/vendor.js:72146:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:72161:15)
    at publish (http://localhost:4200/assets/vendor.js:72129:9)
    at http://localhost:4200/assets/vendor.js:48487:7
    at Queue.invokeWithOnError (http://localhost:4200/assets/vendor.js:16016:18)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:16071:11)
    at Object.DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:15872:17)
    at Object.Backburner.end (http://localhost:4200/assets/vendor.js:15161:25)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:15274:18)
```

**Comment by saschaben** [comment]
:+1:

**Comment by stopfstedt** [comment]
:+1: LGTM

**Comment by stopfstedt** [comment]
@homu r+

**Pull request merged**
