### PR TITLE
Reformatted Session List

### LINKED ISSUE #3847: Allow session title to be edited from session list
In the session list on the courses page it would be nice to edit the session title.

### LINKED ISSUE #3849: Split session list into two views
We should provide two very different views of the sessions in a course:
1) The current static table
2) A dynamic grid which is expanded and editable

### PR DESCRIPTION
**Pull request by jrjohnson**
Reformat the session list to be more compact and include more information. When a session is expanded compact the offering display and make some parts editable.

Work in progress:
- [x] Review basic format and concepts
- [x] Replace HTML table with CSS grid to give more control of the format
- [x] Update tests, write new tests
- [x] User feedback
- [x] Offering Manager edit action should only show up when users have permission to edit
- [x] Needs Translations 
```
'durationHours': { 'one': '1 hour', 'other': '{{count}} hours'},
'durationMinutes': { 'one': '1 minute', 'other': '{{count}} minutes'},
'when': 'When',
```

Fixes #3847 
Fixes #3849

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit e021256dd5b9b4dc8413cb8a3346bad9a46e11a7

https://deploy-preview-3883--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
@jrjohnson https://stackoverflow.com/questions/20503424/positionfixed-not-working-in-google-chrome

**Comment by jrjohnson** [comment]
@saschaben / @dartajax there is still lots to do here, but please take a look at the overall picture of the list of sessions and the expanded offering table and let me know what you think.

**Comment by saschaben** [comment]
still not quite prime time: needs some layout fine tuning, but more importantly we still have some visual clutter & confusion between the data display for collapsed and for open lines:

newsessiongrid

Let's discuss: I think we still need to to a method of providing better clarity to these differing datasets before we take it to the users for feedback.

**Comment by jrjohnson** [comment]
More feedback from group review:

- [ ] Expand all when expanded has wrong icon
- [ ] More padding between rows
- [ ] Not enough padding on delete confirmation
- [ ] only one offering can be edited at a time
- [ ] 0 minutes shouldn't show up
- [ ] Can click on a time block and change times for every offering in that block
- [ ] try and fit some instructors names
- [ ] don't seperate out duration data, put it up top with the date
- [ ] No expander when there are no offerings
- [ ] Improve the visual relationship between and expanded row and its offerings to better differentiate multiple expanded rows.
- [ ] Zebra stripe missing from session grid

**Comment by saschaben** [comment]
Latest feedback:

- No delete action for offerings -- hard to get to (no delete in offering mgt panel either, only in regular session edit mode). could be a point of contention / confusion. Not a blocker but let's discuss.

- return screen from full offering edit page focus target at bottom rather than top of previous target. Makes the return a bit jarring. 

layout layering (z-index) issue:

layout1

- Offering Instructor Name:

layout2

- Open All opens even the ILMs / sessions with no offerings. Not a big deal or blocker, but a little odd for UX, and want to make sure you are aware:

layout3

**Comment by stopfstedt** [comment]
feedback from today's user meetup:

- rather than showing start date/time and duration, show start date/time and end date/time. or end date/time _in addition_ to duration (just like on the offering editor)

- **bug**: after editing a group of offerings via the embedded form, it drops the user off somewhere on screen in the list. seemingly arbitrary. focus should be set on the last edited session.

**Comment by stopfstedt** [comment]
assigned to @dartajax for another round of click testing.

**Pull request merged**
