### PR TITLE
list out all mapped competencies, not just the one linked to the firs…

### PR DESCRIPTION
**Pull request by stopfstedt**
…t project year objective.

fixes https://github.com/ilios/ilios/issues/5304

image

image

image

### CODE REVIEW

**Comment by stopfstedt** [comment]
@dartajax - may be relevant for screenshots in the user-guide: this one relabels a column header from "Competency" to "Competencies".

image

**Review by jrjohnson — APPROVED** [review]
Nice. I was worried this was gonna require a *lot* more to fix. LGTM, but I didn't test the actual output, just looked at the code.

**Comment by dartajax** [comment]
https://deploy-preview-7701--ilios-frontend.netlify.app/data/courses/2141

^^^ try testing the visualizations with the above-referenced - some course objectives have multiple parents - many have zero parents - I can get console msg but wanted to see if you wanted to check that scenario out - @stopfstedt

**Comment by dartajax** [comment]
`Error in parsing value for ‘overflow’.  Declaration dropped.`

**Comment by stopfstedt** [comment]
> https://deploy-preview-7701--ilios-frontend.netlify.app/data/courses/2141
> 
> ^^^ try testing the visualizations with the above-referenced - some course objectives have multiple parents - many have zero parents - I can get console msg but wanted to see if you wanted to check that scenario out - @stopfstedt

Good find, Dave. the `NaN` situation is another bug, but it's unrelated to multi-objective mapping. will deal with it separately.

**Review by jrjohnson — APPROVED** [review]

**Pull request merged**
