### PR TITLE
Combined publication status and menu for courses and sessions

### LINKED ISSUE #291: Course & Session Detail Header Clean Up / New Publish Buttons
Here are all the states (and I added styling annotations too)  Sascha - if you approve, please assign to JJ.  I'm recommending styling the background color on hover of menu items that are either "dangerous" or desired.  Blue bg is neutral...

publish-button-options

### PR DESCRIPTION
**Pull request by jrjohnson**
No tests since they won’t run anyway.

Also needs styling work - especially on the edge as the menu runs over, but I will leave that for @jenzweben hopefully.

Fixes #291

### CODE REVIEW

**Comment by saschaben** [comment]
First note: Select drop-down does not close after selection.

**Comment by jrjohnson** [comment]
I fixed the click close issue.  The style problem is beyond my capabilities.  Hopefully after it is merged @jenzweben can do the magic she did to fix the action menu disappearing at the bottom of the screen.  I think its the same issue, just horizontal this time.

**Comment by saschaben** [comment]
Session publish control is displaying "scheduled" as "published" and vice versa:

ilios 2015-03-16 08-36-26

ilios 2015-03-16 08-40-08

To recreate: take any session, set to "publish", then change state to "Scheduled". Only occurs when shifting from published to scheduled  or scheduled to published state. Going from unpublished to either published state displays properly.

**Comment by jrjohnson** [comment]
@saschaben I'm guessing this is related to #289.  I didn't touch the functionality here, just the display.

**Comment by saschaben** [comment]
@jrjohnson  you are right: will add this description of the issue to the bug ticket (rather than creating a dupe).

**Comment by saschaben** [comment]
I think #289 needs to be fixed before we can merge this.

**Comment by jrjohnson** [comment]
@saschaben - this is ready to check again.  Should be fully functional now, plus I added tests!

Fixes #289

**Comment by saschaben** [comment]
looks good, review and merge!

**Comment by saschaben** [comment]
When reviewing against the vagrant API, 

1. Switching publish state on a course removes all sessions from the course display.
 initial state:
sample1
update course to scheduled: no issues. Switch to unpublish:
sample2
2. attempting to use the publish control after this consistently throws an error:

ilios 2015-03-17 21-16-53

between the memory issues on this machine, and the apparent fragility of the test setup with vagrant and ember at this stage, it is challenging to tell whether this is an environmental failure or a code issue.

**Comment by jrjohnson** [comment]
@saschaben  you can't really test changing the state against the vagrant API as the update endpoints for publishEvent and most of session are not complete.  The vagrant setup only handles pulling data, not modifying it.

**Comment by saschaben** [comment]
@jrjohnson OK then! 

In that case, I think we are good to go.

**Pull request merged**
