### PR TITLE
Ability to active/de-activate session types

### LINKED ISSUE #3063: Session Type De-Activation Functionality Needs To Be Added
Here is an ugly mock showing what it would look like with a toggle on the Session Type detail. I am not saying this is what it should appear to be like but it does demonstrate the desired functionality.

image

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #3063 

Session type form:
selection_378

Session type list:

selection_380

Session editor:

selection_381

New My-report

selection_382

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 53b96663717fcc340bcf00c7fc61d61655bdd1b8

https://deploy-preview-3169--ilios-frontend.netlify.com

**Comment by stopfstedt** [comment]
@saschaben - soliciting feedback on the UI changes so far before i proceed updating test coverage. does this meet the mark? are there any other areas where deactivated session types need to be labeled/de-prioritized?
thanks.

**Comment by saschaben** [comment]
Will provide further feedback shortly, but right now; language should be "active / inactive”; also select lists not working on new or edit but I am on my phone, so....

**Comment by saschaben** [comment]
scratch the last comment re select lists -- didn't realize that all the session types had been set to deactivated.

So: labeling change to "active" and "inactive" vs the current "activated / deactivated", otherwise I think this covers it.

**Comment by saschaben** [comment]
FYI: for translation files: FR: `Actif`, `Inactif`

**Pull request merged**
