### PR TITLE
Add a Medium Editor to text area elements

### PR DESCRIPTION
**Pull request by jrjohnson**
**UPDATE 5/26:**
good to go with medium editor. Issues to address are:
1. when you click to manage it needs to open the editor immediately, rather than requiring two clicks to open the editor.
2. we need to provide a plain text editor option along with WYSIWYG
3. Objective display needs to show styling
4. we need to find an appropriate means of scrubbing existing extraneous code tags from the objective data, along with our cut&paste solution to scrubbing new input data.

**Solutions**
- determine a tag whitelist for accepted markup
- find a means of both scrubbing and validating the scrub

QUESTIONS:
can we do this without users having to look and approve?
can we add a column to track cleansing of data?

*Try out the medium editor when changing objective titles.*

*Thoughts?*

Refs #458

### CODE REVIEW

**Comment by saschaben** [comment]
Hmmm. first thoughts:

1. the box around the text doesn't appear without a second click --- a little hard to understand what's going on. If we can, we should probably set this so that the box border shows up on the first editing click in the text.
2. the controls are applying the HTML, but the tags aren't being displayed. hard to judge because of this.
3. the inability to control font-family is annoying for the existing cut and paste cruft that exists. It would be great if we could somehow force this type of stuff into conformity....
4.. if we can tweak things a little per above, then I think that with the current control ribbon we should be OK for an initial release.

Overall: YAY an editor!!!!!

**Comment by jrjohnson** [comment]
Yes, I think we're going to have to contribute a fair amount of code or else create our own addon to get this to play well with Ember.   I want to make sure we're on the right path before digging into that.  The essential thing to take away is the 'Medium Editor' toolbar.  Which appears over highlighted words as opposed to at the top of the editing area.  Does this make sense as a pattern?

The other issue here for me is that after you save you can only see the plain text.  I think in order to use this kind of editor which hides the HTML we're really going to need to display the formatted text on the list of objectives.

So lots to discuss, but maybe we're on the right track.

**Comment by saschaben** [comment]
Yeah.

Lots of good links to discussion if you Google "ember-cli wysiwyg editor". I'm open to radical choices here if they answer our needs

**Comment by jrjohnson** [comment]
Closing - @ebryn will look to see what the best solution is.

**Pull request closed without merging**
