### PR TITLE
Focus on the search box when the icon is clicked

### LINKED ISSUE #494: Search Box Icon Select-ability
During usability testing, Gitanjali was trying to search for a Director to add and clicked on the search icon.  She was then unable to type in the search field because she thought she had already selected it.

Sooo.  We need to implement the search field in a way that puts the cursor in the input area when they click on either the search icon OR the search box input area...

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #494

### CODE REVIEW

**Comment by saschaben** [comment]
works for me!

**Comment by dartajax** [comment]
This is only for search boxes I take it.  Should we have or do we already have a ticket for the setting focus on inline editing fields automatically?

**Comment by jrjohnson** [comment]
@dartajax -yes search box only.  If there isn't a ticket for inline edit already please create one.

**Comment by dartajax** [comment]
The inline edit ticket is #446.

**Pull request merged**
