### PR TITLE
Fix recently updated agenda itesm

### LINKED ISSUE #1383: Calendar List view shows "recently updated" on all events
the list view of the calendar on the dashboard is showing the "recently updated" icon against ALL events, and not correctly testing for the date range. 

Regular Calendar view is fine.

### PR DESCRIPTION
**Pull request by jrjohnson**
Users logging into Ilios will no longer see every single event as recently updated.  

I also add a loading indicator so it does not just say none until it loads.

Fixes #1383

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please review

**Comment by saschaben** [comment]
:+1:  LGTM

**Comment by jrjohnson** [comment]
@djvoa12 for some background on this check out http://locks.svbtle.com/to-attrs-or-not-to-attrs

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
