### PR TITLE
Better Cohort Manager

### LINKED ISSUE #146: Close cohort picker on course details?
Once a user clicks the add new button for course cohorts the picker will be open forever.  Do we want to provide a close option?  

We could:
a. Change the button when the picker is open - 'Close New' or whatever
b. Add a big x next to it to close it.

@jenzweben - your choice.  I can add the control and you can handle any style.

### PR DESCRIPTION
**Pull request by jrjohnson**
Used the in place pattern for modifying cohorts for a course.

Fixes #146

### CODE REVIEW

**Comment by thecoolestguy** [comment]
builds well.... looks good... please verify functionality...

**Comment by saschaben** [comment]
when a cohort is removed from a course, it's parent objective relationships need to be removed as well.

Additionally, when we get around to  dealing with offering management, we'll need to address decoupling groups of a given cohort when it is removed from a course (and providing alerts to note same to user).

**Comment by jrjohnson** [comment]
@saschaben - Removing a cohort will now delete parent objective references for course objectives.

**Comment by saschaben** [comment]
looks good. Merging.

**Pull request merged**
