### PR TITLE
Expand all of the sessions in the list

### LINKED ISSUE #3815: Expand all sessions
Add a link to the top of the list of sessions to expand all - currently you have to click each row in the session list table individually to open them.

### LINKED ISSUE #3822: Need Spinner Or Loading Indicator for Sessions List
When applying the soon to be included `Expand All` functionality on a Session List, it takes a while for the session list to open. 

Actually even applying a sort order adjustment on a large Course take enough time to warrant an indicator that something is happening - a spinner or loading indicator of some sort.

### PR DESCRIPTION
**Pull request by jrjohnson**
This makes it much easier to scan all of the offerings and determine if
there are any issues.

Fixes #3815
Fixes #3822

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 13e79eb67c77e6bbe2a8673c48ec2d44e297acd8

https://deploy-preview-3819--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
Since we already use the "expand" icon in the header to note sort order, we probably need to use something else (just in the header) as the "expand all" icon. Maybe fa_list, or fa_indent?

**Comment by jrjohnson** [comment]
@saschaben replaced the icons, please take another look.

**Comment by saschaben** [comment]
Love the new icons!

**Comment by stopfstedt** [comment]
selection_008
when "expand all" button is used, it creates a huge white gap underneath the bottom orange line.

**Pull request merged**
