### PR TITLE
default message for no available learner groups

### LINKED ISSUE #1004: If Cohort Missing Add Offerings Screen Needs To Have Msg To Assist
A blue line is displayed where the Learner Group picker would ordinarily appear and there is no message indicating that a missing cohort is what is causing this situation.

See screen shot below ...

nocohort

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #1004 

screen shot 2015-11-15 at 5 11 15 pm

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben can you provide text to use in this case (when there are no cohorts attached to a course and the small group generator is used)?

**Comment by saschaben** [comment]
I think we can leave the default message as "No learner groups available; No cohort is attached to this course." The error messaging for small group generation without learner groups selected will handle further messaging, and direct users to switch to the "offering" button to create offerings without group associations.

FR: "Pas de groupes d'étudiants sont disponibles; pas de cohorte est attaché à ce cours ."

**Comment by djvoa12** [comment]
Ready for review.

**Comment by jrjohnson** [comment]
:+1: reviewed at http://564a682a71e20a1ba9000077.ilios-frontend.netlify.com/courses/551

**Comment by jrjohnson** [comment]
@homu r+

**Comment by jrjohnson** [comment]
@homu retury

**Comment by jrjohnson** [comment]
@homu retry

**Pull request merged**
