### PR TITLE
Stop using PostCSS

### PR DESCRIPTION
**Pull request by jrjohnson**
This reverts our move to PostCSS and returns to ember-cli-sass to
compile our styles. PostCSS is great, but the sass plugin is abandoned
and has very outdated dependencies as well as not being compatible with
the latest PostCSS version. Until we're willing to re-write entirely in
non-sass this isn't a good path for us.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax this needs an in-depth click test to ensure there are no style issues anywhere. I've assigned it to you for that initial review because the code itself hasn't changed at all.

**Comment by dartajax** [comment]
Got it. Gonna test now.

**Comment by jrjohnson** [comment]
Thanks @dartajax I'm figuring out the build issue here and then I'll move this forward.

**Comment by dartajax** [comment]
Been testing on Safari - seems ok.

**Review by stopfstedt — APPROVED** [review]

**Pull request merged**
