### PR TITLE
Session Detail Page First Draft

### PR DESCRIPTION
**Pull request by jrjohnson**
This isn't done, but it is a start.  Everything but the offerings should be there and working.

I wanted to get something merged to we can take a style pass and also ensure that styles and functionality applied to course details are working for both course and session.

Refs #150

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/197" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
We may need to revisit the Session Objective display --- the 1:1 relationship of objective to parent works for this display in course, but the 1:many session relationship makes this display model ineffective.

**Comment by saschaben** [comment]
I know all the technical reasons why we are loading a new page for session, but...since the course header is not persistent, and re-loads along with the session content, this creates a jarring contectual displacement for the user. And since we lose the context of location within a larger set of sessions in a course as well, we may have to rethink this a little. At the least we are going to need to re-label everything as "session-this" and "session-that".

**Comment by saschaben** [comment]
Also: getting a lot of navigation errors when going back and forth from course page: " Error: Assertion Failed: calling set on destroyed object"

**Comment by saschaben** [comment]
Missing functionality to set as Independent Learning, with instructional time instead of duration -- assuming we will handle this along with offerings?

**Comment by jrjohnson** [comment]
@saschaben yes I agree that the transition is not working.  That's one of the reasons I wanted to get this out for discussion.  The mocks also have the course edit drop-down being available from this location, but I think maybe the right choice is to take the course off this page entirely except for the title.  I'm especially worried about the double publish buttons and status at the top, they are very confusing.

As far as ILM goes, I'm not sure we've added that functionality anywhere in the mocks.

**Comment by saschaben** [comment]
@jrjohnson agreed and agreed: lots of challenges. None insurmountable. we will use Monday as our review session for this page, perhaps do some real time updating as a group. I believe @dartajax has already added a ticket for the missing ILM function, but we should review regardless, as we need to determine whether it goes in with the offering tools or with the general session tools.

This a a great start.

**Comment by jrjohnson** [comment]
@saschaben this is ready for another review

**Pull request merged**
