### PR TITLE
updated done/cancel button styles to be red and green, fixes #421

### LINKED ISSUE #421: Update Cancel / Done Button Style
See mock - style guide included

new-save-cancel-buttons

### PR DESCRIPTION
**Pull request by thecoolestguy**

### CODE REVIEW

**Comment by saschaben** [comment]
Looks good, but inline edit cancel icon ("red x") now has a button border. Can we fix that class prior to merge?

**Comment by saschaben** [comment]
If not, I'll merge and add a bug ticket.....

**Comment by thecoolestguy** [comment]
yeah, I'll fix that now

**Comment by thecoolestguy** [comment]
This should be fixed now and not producing a border on the icon-based cancel/done buttons"

**Comment by saschaben** [comment]
much better. The cancel icon still however takes up as much space as a button, leaving a large gap between the icons. can this be tightened up -- give the class a left-align or less width?

**Comment by saschaben** [comment]
looks good from here now!

**Pull request merged**
