### PR TITLE
added more validations

### PR DESCRIPTION
**Pull request by djvoa12**
- [x] ILM Session Instruction Hours
  - Location: `/courses/595/sessions/16580` in `session-overview`, set __Independent Learning__ toggle to `yes`; check value for __Hours__.
  - Criteria: numbers only, greater than 0, can't be blank, decimal value okay
- [x] Session Title
  - [x] Location 1 (create): `/courses/595`
  - [x] Location 2 (edit): `/courses/595/sessions/16523`
  - Criteria: required, min length 3, max 200, all valid chars acceptable
  - Note: `ilios-sessionl-list` and `new-session` components have been altered significantly
- [x] Course Title
  - [x] Location 1 (create): `/courses`
  - [x] Location 2 (edit): `/courses/595`
  - Criteria: required, min length 3, max 200, all valid chars acceptable
- [x] Program Title
  - [x] Location 1 (create): `/programs`
  - [x] Location 2 (edit): `/programs/1`
  - Criteria: required, min length 3, max 200, all valid chars acceptable
  - Note: `programs` and `new-programs` have been altered significantly
- [x] Program Short Title
 - Location: `/programs/1`; in the overview section review __Program Title (Short)__
  - Criteria: optional, min > 1, max = 10
- [x] Learning Material Author
 - Location: `/courses/595?details=true`; scroll down to __Learning Materials__; click the `Add` button and select `File/Weblink/Citation`; Review __Content Author__
  - Criteria: required, min 2 char, max 80, any character allowed
- [x] Learning Material Display Title
 - Location: `/courses/595?details=true`; scroll down to __Learning Materials__; click the `Add` button and select `File/Weblink/Citation`; review __Display Title__
  - Criteria: required, min > 3, max = 60

### CODE REVIEW

**Comment by saschaben** [comment]
Added routes to validations above.

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@djvoa12 there is a legitimate test failure here, can you take a look?

**Comment by jrjohnson** [comment]
:+1: approved by @saschaben

**Pull request merged**
