### PR TITLE
Improved Admin Dashboard

### PR DESCRIPTION
**Pull request by jrjohnson**
Make it clear how to manage users and highlight that important
functionality.

- [x] Requires #1557 for button titles and correct bulk manage link
- [x] Needs translations

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax Aside from missing translations for some button names this is ready for a review of the style and functionality.

**Comment by saschaben** [comment]
buttons/links in user search box not working (not active). fast search working fine though. error trapped in inspector: `Failed to parse SourceMap: http://localhost:4200/assets/vendor.map`

**Comment by jrjohnson** [comment]
@saschaben buttons fixed and style improved.  Take another look everything should work now.

**Comment by saschaben** [comment]
styles much improved!

Functionality is all good!

👍

**Comment by stopfstedt** [comment]
LGTM

**Pull request merged**
