### PR TITLE
Scaffolding for acceptance tests

### LINKED ISSUE #248: Design better consistent display for parent objectives
Need a way to display one or more parent objectives that is consistent and does not cause a context break between showing one and showing many.

For course: as discussed, let's go with the current _Parent Obj. Text (Parent Competency)_ when only one parent chosen (ie only one cohort), and _Name of Cohort (Parent Comepetency)_ for more than one, along with some sort of tooltip / info link to show full info. should use ellipsis on these as well.

For session: we need something that will be more generic for both 1 or 1+n patterns, that won't discourage the actual linking of multiple parents, nor make the content of those parents completely opaque.

### PR DESCRIPTION
**Pull request by jrjohnson**
Created a Pretender server which will handle all data requests during tests.
Modified the current-user service to use ic-ajax so we can mock the call for the current session
Added an initial set of tests for /courses as a demonstration

Fixes #248

### CODE REVIEW

**Comment by thecoolestguy** [comment]
When building this PR, I got the following Babel warnings:

```
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/ilmSessions.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/learningMaterials.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/meshDescriptors.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/meshTerms.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/objectives.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/offerings.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/recurringEvents.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "ilios/tests/fixtures/users.js" as it exceeds the max of "100KB".
```

My be able to avoid them by setting 'compact' to false... See here: https://github.com/babel/babelify/issues/62

**Comment by thecoolestguy** [comment]
Also got the following jshint error before the build finished:

```
helpers/start-server.js: line 9, col 20, 'Pretender' is not defined.

1 error

===== 1 JSHint Error
```

**Comment by jrjohnson** [comment]
@thecoolestguy - The babel errors can be ignored.  Its only possible currently to set the entire project to compact: false - and apparently thats not a great idea.  The warnings only tell us that those files are being treated as compact: false.  Plus its a good reminder that these fixtures still need work to be slimmed down.

You probably need to restart your ember server - I modified JSHint and Broccoli files to hopefully avoid that error and also build faster.

**Comment by thecoolestguy** [comment]
that did it!  (and also added pretender)  Good job!  Merging...

**Pull request merged**
