### PR TITLE
Fix pager for unassigned students to show the right total

### LINKED ISSUE #1475: Admin Console Total Record Count Does Not Get Updated
See the screen shot below ...

It should be Showing 1 - 158 of 158 and not Showing 1 - 162 of 158, which is not possible mathematically.  The "162" count did not refresh.

image

### PR DESCRIPTION
**Pull request by jrjohnson**
We were not counting students who had been saved so the total count was
always wrong once any action had been taken.

Fixes #1475

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 20c24e9830c8daf5cdc6097902ba34df1297f628

http://deploy-preview-2202.ilios-frontend.netlify.com

**Comment by saschaben** [comment]
We still have an error in the following use case:

- go to `/admin/assignstudents?school=1`
- select multiple users for assignment
- hit save

at this point everything is great, then --

- update pagination from "25 of _n_" to "50 of _n_'
- the value of _n_ reverts to the previous total before saves were transacted.

**Comment by jrjohnson** [comment]
@saschaben ready for testing again.

**Comment by saschaben** [comment]
LGTRS (looks good to Rico Suave) 👍

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
