### PR TITLE
Inline and Download links for PDF learning materials

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #3038 

My Materials:
selection_370

Learning Materials manager:
selection_371

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit c038ee84df47524b2545d8c57e4cccae4633e06e

https://deploy-preview-3162--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
this looks great. Let's get this in place everywhere!

**Comment by dartajax** [comment]
any chance we could put a mouse-over caption to explain this ... 
image

**Comment by dartajax** [comment]
or what is that supposed to do? copy the file to the clipboard?

**Comment by dartajax** [comment]
image

**Comment by dartajax** [comment]
we should do a mouse-over caption over the file name too to indicate to the user that it will open inline - rather than think they can interpret the URL at the bottom of the screen -- are these suggestions possible or out of scope?

**Comment by saschaben** [comment]
@dartajax is right -- the copy icon should have a mouseover of "copy link"

**Pull request merged**
