### PR TITLE
Fix multiple issues with CI overview description field

### LINKED ISSUE #1986: Edit Description Does Not Work - Delete Key Sends To End of Description
Relates to #1987, #1988, #1989. 
Step One:  Planning to Edit the Description (get rid of MD).  Click Description to edit as shown below.

image

Step Two:  Click with Mouse to put Cursor into the Description field to delete "MD" from the Description.

image

Step Three: Using the keyboard hit "Delete".  The results of that action are what is shown in the screen shot below.

image

The "M" did get deleted (removed from the screen anyway).  But the great part is the cursor has now shot to the end of the string.

This does not always happen.  I had a hard time reproducing it.

### LINKED ISSUE #1987: Cancel And Save Buttons Don't Function -- Edit Description CI
This is related to #1986 since once that occurs, the Save and Cancel Buttons no longer function.  Maybe they are related.  Maybe not.  Either way, see below. Also related to #1988, #1989.

Click the Cancel button and the cursor exits the Description field but no cancellation occurs.

image

The Save button fares no better in this state.  The screen stays like this - need to refresh.  And I do too.

### LINKED ISSUE #1988: Can't Navigate Back to Reports After Edit Attempt Made on CI Report Description
In all likelihood this is related to #1987 and #1986 and #1989.  

Same as before, delete the "M" from "MD" and click either Save or Cancel button(s).

image

Now click "Back To Reports"

Here is the error ...

image

I have received uglier errors (more of them) than this on other attempts; but either way, it is probably related to the non-functioning Save and Cancel buttons.

### LINKED ISSUE #1989: CI Report Title Disappears When Events Related to the Previous Three Bugs Occur
I noticed this also - probably related to #1988 #1987 #1986.

Report Title "circled" in Blue.
image

Expose #1986 by attempting to delete "MD" from the title.

Expose #1987 by clicking cancel.

image

Now, look at the screen.

image

Download and Finalize have moved way over to the left due to the fact that the Title has been removed from the Screen.

### PR DESCRIPTION
**Pull request by jrjohnson**
Several problems here, the cursor was umping when editing, changes were not being saved, and reverting changes was breaking the whole page.

Fixes #1986
Fixes #1987
Fixes #1988
Fixes #1989

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please test to ensure all issues were resolved.

**Comment by dartajax** [comment]
LGTM :+1:

**Comment by dartajax** [comment]
I have tested this and if cool with you all, I will merge the pull request once the tests have passed.  Cool?

**Comment by stopfstedt** [comment]
i accept this.

**Pull request merged**
