### PR TITLE
Don't delete values when editor is opened and then closed

### LINKED ISSUE #1078: Froala Validation Error on Save
This occurs in Session Objective and Session Description ...

image

Click the Description above to edit it.

image

Click Done without editing any information in the field.

It removes whatever was there.

image

Click to edit.

It's gone.

image

I had the Inspect Element running but did not pick anything up in Console or Network.

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #1078

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please review at:
http://56451089d6865d3e9e00003c.ilios-frontend.netlify.com

**Comment by dartajax** [comment]
Using the netlify URL above, I found the following things to have happened so I cannot approve this pull request.

http://56451089d6865d3e9e00003c.ilios-frontend.netlify.com/courses/595

image

http://56451089d6865d3e9e00003c.ilios-frontend.netlify.com/courses/595/sessions/17549

image

image

Click to Edit.

image

image

Repeat.

image

Now it's gone ...

image

**Comment by jrjohnson** [comment]
@dartajax please test again at http://564634ddd6865d2f8d00009d.ilios-frontend.netlify.com

**Comment by dartajax** [comment]
:+1:

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
