### PR TITLE
Fix the publish all counts and saving actions

### LINKED ISSUE #925: "ignore" count in Publish all sessions is incorrect
looks to be pulling the "schedule" count instead of the actual ignore count.

pub_err1

### PR DESCRIPTION
**Pull request by jrjohnson**
The confirmation counts should now be correct.  When a save is
successful the user is redirected back to the course.

Fixes #925 #1022

### CODE REVIEW

**Comment by saschaben** [comment]
OK. had a weirdness that I cannot reproduce, but the first time I looked at a course, the section numbers were:

pub1

... and the corresponding button numbers were:

pub2

I don't know why or how the two numbers were off by a count of 1, and I cannot seem to make it happen again.

**Comment by saschaben** [comment]
:+1:

**Comment by thecoolestguy** [comment]
@home r+

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
