### PR TITLE
Fix issues saving program year

### LINKED ISSUE #1142: Unalbe to add directors to NEW program year
When a new program year has just been created it isn't possible to add directors to it.  Once the page has been refreshed it is.

Moved from ilios/ilios#1119

### PR DESCRIPTION
**Pull request by jrjohnson**
Adding director to program year needed to be encapsulated correctly in a promise.

We were attempting to save the competency along with the program year which runs into permission problems.

Also added the spinner when saving.

Fixes #1142

### CODE REVIEW

**Comment by saschaben** [comment]
OK. Setting a program year as "Mark as scheduled" now athrows an error: 

`publishTarget.save is not a function`

This appears to happen for any PY when you do anything with the publish actions; a hard refresh will clear the problem and allow proper saving/publishing/whatever.

**Comment by jrjohnson** [comment]
@saschaben please review again.  I think it should work now.

**Comment by saschaben** [comment]
OK. Better. But --- when adding a competency to a program objective, the relationship saves but returns an error page:

```
There are 5 errors
Adapter operation failed

Status Code: 500
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:31786:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:143031:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:144749:16)
    at hash.error (http://localhost:4200/assets/vendor.js:144845:33)
    at fire (http://localhost:4200/assets/vendor.js:7784:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:7896:7)
    at done (http://localhost:4200/assets/vendor.js:13952:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:14354:8)
Adapter operation failed

Status Code: 500
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:31786:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:143031:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:144749:16)
    at hash.error (http://localhost:4200/assets/vendor.js:144845:33)
    at fire (http://localhost:4200/assets/vendor.js:7784:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:7896:7)
    at done (http://localhost:4200/assets/vendor.js:13952:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:14354:8)
Adapter operation failed

Status Code: 500
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:31786:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:143031:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:144749:16)
    at hash.error (http://localhost:4200/assets/vendor.js:144845:33)
    at fire (http://localhost:4200/assets/vendor.js:7784:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:7896:7)
    at done (http://localhost:4200/assets/vendor.js:13952:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:14354:8)
Adapter operation failed

Status Code: 500
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:31786:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:143031:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:144749:16)
    at hash.error (http://localhost:4200/assets/vendor.js:144845:33)
    at fire (http://localhost:4200/assets/vendor.js:7784:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:7896:7)
    at done (http://localhost:4200/assets/vendor.js:13952:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:14354:8)
Cannot read property 'top' of undefined


TypeError: Cannot read property 'top' of undefined
    at http://localhost:4200/assets/ilios.js:88548:64
    at fn (http://localhost:4200/assets/vendor.js:15478:20)
    at Queue.invokeWithOnError (http://localhost:4200/assets/vendor.js:16018:18)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:16073:11)
    at Object.DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:15874:17)
    at Object.Backburner.end (http://localhost:4200/assets/vendor.js:15163:25)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:15276:18)
    at Object.Backburner._runExpiredTimers (http://localhost:4200/assets/vendor.js:15674:12)
    at Backburner._boundRunExpiredTimers (http://localhost:4200/assets/vendor.js:15129:13)
```

**Comment by saschaben** [comment]
Deleting a program year fails: 
```
There is 1 error
Cannot read property 'set' of undefined

TypeError: Cannot read property 'set' of undefined
    at remove (http://localhost:4200/assets/ilios.js:7143:25)
    at _emberViewsViewsView.default.extend.send (http://localhost:4200/assets/vendor.js:62842:54)
    at runRegisteredAction (http://localhost:4200/assets/vendor.js:39470:25)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:15270:25)
    at Object.run [as default] (http://localhost:4200/assets/vendor.js:36126:27)
    at Object.actions.push.handler (http://localhost:4200/assets/vendor.js:39462:39)
    at HTMLSpanElement.<anonymous> (http://localhost:4200/assets/vendor.js:61798:27)
    at HTMLBodyElement.jQuery.event.dispatch (http://localhost:4200/assets/vendor.js:9306:9)
    at HTMLBodyElement.elemData.handle (http://localhost:4200/assets/vendor.js:8974:28)
```

**Comment by jrjohnson** [comment]
Adding competency is a new issues. I'm not sure about deleting. I will investigate.

**Comment by jrjohnson** [comment]
@saschaben I fixed the deleting and created ticket #1176 for the issue with program year objective competency.  Please test again.

**Comment by saschaben** [comment]
Still can't delete:

```
There is 1 error
Cannot read property 'set' of undefined

TypeError: Cannot read property 'set' of undefined
    at remove (http://localhost:4200/assets/ilios.js:7143:25)
    at _emberViewsViewsView.default.extend.send (http://localhost:4200/assets/vendor.js:62842:54)
    at runRegisteredAction (http://localhost:4200/assets/vendor.js:39470:25)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:15270:25)
    at Object.run [as default] (http://localhost:4200/assets/vendor.js:36126:27)
    at Object.actions.push.handler (http://localhost:4200/assets/vendor.js:39462:39)
    at HTMLSpanElement.<anonymous> (http://localhost:4200/assets/vendor.js:61798:27)
    at HTMLBodyElement.jQuery.event.dispatch (http://localhost:4200/assets/vendor.js:9306:9)
    at HTMLBodyElement.elemData.handle (http://localhost:4200/assets/vendor.js:8974:28)
```

**Comment by jrjohnson** [comment]
It is program years with courses attached which the DB will not cascade the deletion of.  I created a new issue for this at #1177

**Comment by saschaben** [comment]
OK. I believe that the deletion and competency parent issues are related -- solve one, solve the other. 

:+1:

**Pull request merged**
