### PR TITLE
Add sorting to session list

### LINKED ISSUE #1261: Sort By Columns Needed on Sessions
This is related to #98 -- going to break it out into separate issues.

For Session, should allow sort by: 
Title | Type | Groups | First Offering | Offerings | Status

The values selected should be sticky and as such should retain the user's choice during the current session with Ilios.

### PR DESCRIPTION
**Pull request by jrjohnson**
Sessions can be sorted by title, type, group count, first offering
date, and offering count.

Refs #1261

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben give this a look sorting the sessions list.  I just want to get some feedback before I add it to the course list as well.

**Comment by jrjohnson** [comment]
I'm not going to have time to do the courses list.  This is ready for review.

**Comment by jrjohnson** [comment]
Turns out this doesn't fully address the session sorting ticket the sort fields are not sticky and there is no sorting by status.  This can be merged now and those things addresses later if we want it to be available ASAP.  Otherwise just assign back to me and I will address the remaining items as time permits.

**Comment by saschaben** [comment]
reviewing now. we need to get something in, so if this passes I think we push this as a part I and address further sorting later. By date is the critical fix in any case.

**Comment by saschaben** [comment]
:+1:

**Comment by saschaben** [comment]
@dartajax please merge

**Pull request merged**
