### PR TITLE
replaced Promise implementation in Courses controller

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #2034

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 5751328e1b93cefe0e649514af8ee8f429b6b2ef

https://deploy-preview-2700--ilios-frontend.netlify.com

**Comment by stopfstedt** [comment]
@dartajax please click test the following in the course manager:
- add a course
- delete a course
- filter courses
- sort courses

**Comment by dartajax** [comment]
the delete action failed on newly created and existing courses

**Comment by stopfstedt** [comment]
@dartajax i fixed the regression that was breaking course deletion. please click-test this component again according to the criteria listed in the comment above. thanks!

**Comment by stopfstedt** [comment]
@jrjohnson please code review. thanks!

**Pull request merged**
