### PR TITLE
Working MeSH search for course

### LINKED ISSUE #144: Fix adding mesh to course
Needs:
1. Correct Translation for the search prompt
2. Fix search box style it is a little blown up
3. Add searchTerm to the mesh API like we have for users.
~~4. Style the returned results appropriatly.~~ (moved to #214)

@jenzweben please attach your mock for the add mesh on the course detail page.

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #144

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/213" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
is the ninja star on this for code review? If so please assign to me for UI review

**Comment by jrjohnson** [comment]
@saschaben - currently only returns mesh descriptor name.  We will have to clean up mesh API before adding further info to the search results.

**Comment by thecoolestguy** [comment]
code looks good... @saschaben, please verify functionality, star, and merge!

**Comment by saschaben** [comment]
Search: PASS. appears to work as desired.
Cancel search: FAIL. cancel clears the search box, but does not clear/close the results box. 

Let me know if you want to merge this as is and add a bug report for cancel function, or if the cancel code is part of this PR

**Comment by saschaben** [comment]
...and after looking at the code, I've created a bug for that close issue with #242 .

merging search code.

**Pull request merged**
