### PR TITLE
Simplified button styles

### LINKED ISSUE #316: hover states for inline edit buttons

### PR DESCRIPTION
**Pull request by jrjohnson**
Removed all the ‘add’ classes from detail buttons - that wasn’t really
doing anything.  Added hover state to inplace edit buttons.  Changed
the inline edit buttons from .save to .done which lets us reuse the
style.

I believe this Fixes #316

### CODE REVIEW

**Comment by dartajax** [comment]
I noticed that the Add New button on Instructor Groups and Student Groups moved over to the left by about an inch on my screen.

**Comment by dartajax** [comment]
And then I found this too ...

what

**Comment by dartajax** [comment]
This is what it looks like currently ...

what1

**Comment by thecoolestguy** [comment]
Code looks good.  Needs final review and merge.

**Comment by saschaben** [comment]
this looks good, seems to check out.

**Pull request merged**
