### PR TITLE
Add Program Detail Page

### LINKED ISSUE #463: Create Program Detail Page
programs-detail

### PR DESCRIPTION
**Pull request by jrjohnson**
Also added program publication check, but its incomplete.

Fixes #463

### CODE REVIEW

**Comment by saschaben** [comment]
looking good. need to address formatting weirdness in header and divider lines, and there is something odd going on with the publish button, but we will review in meeting today and any follow-on issues can be scoped and logged then.

**Comment by jrjohnson** [comment]
@saschaben  - please test again.  I fixed the publish button as well as adding the ability to create new program years.

**Comment by saschaben** [comment]
We need to consider further the disallowing of changing the academic year setting on a program year: I'm a little (but only a little) concerned about the "pick it once and you're stuck" model. Sure, it's easy enough to just delete and recreate -- as long as no work has been done. But for now I think this pattern should be fine.

Otherwise, all good. An interesting side effect of the hard-coded api data: until you add a new program year, publish tool doesn't recognize years as existing, and so does not allow for publish -- even though pre-existing test data is there. As long as this doesn't bleed over into real use, it should be all good.

**Comment by saschaben** [comment]
OK. 99.99% there. I am having a trouble saving a program duration of value = 1; each attempt to select a value of n=1 just reverts back to "click here to edit" default on save. I'm guessing this is due to the defaulting of the select list to the initial value (1). I think this may have been adding to the publish process confusion earlier (since we require duration).

We can go ahead and merge, but please create a new bug ticket to address this in a later prerelease if it's not a super-quick fix that can be slipped in now.

**Comment by jrjohnson** [comment]
@saschaben I'm unable to duplicate the change to 1 issue.  I added a specific test case to check for this so it will run in our browser matrix to detect if this is a browser specific bug.

**Comment by saschaben** [comment]
K. Getting this in Chrome and Safari. you can see the behavior here:

https://www.dropbox.com/s/2z5z365a0wihp4g/n%3D1_screencast.mp4?dl=0

**Comment by jrjohnson** [comment]
@saschaben - ok I think I fixed it.  Give it another look please.  May need to do further refinement on the generic select component we are using here - I added that as #489

**Comment by saschaben** [comment]
got it. current fix now works, default to 4 is a-ok.

**Pull request merged**
