### PR TITLE
swapped position of cancel and done buttons to make 'done' show up first

### LINKED ISSUE #520: Standardize Location of Cancel / Done Text Buttons
For every form Done should be listed first (on the left) and cancel on the right.

### PR DESCRIPTION
**Pull request by thecoolestguy**
fixes #520

### CODE REVIEW

**Comment by saschaben** [comment]
"My name is Sascha Cohen, and I approve of this Pull Request."

**Comment by dartajax** [comment]
Can I merge this?

**Comment by saschaben** [comment]
wait for Travis

**Comment by jrjohnson** [comment]
@thecoolestguy - needs a rebase.

**Pull request merged**
