### PR TITLE
Added learning material editing / details

### LINKED ISSUE #331: Learning material edit
Add the ability to edit the course / session learning material links.  Mock in #143.

However, I think we should be managing learning materials in the same way we are managing objectives - with the slide in edit / undo panel.  @jenzweben @saschaben thoughts?

### PR DESCRIPTION
**Pull request by jrjohnson**
First pass at course and session learning material editing.  No style has been applied yet.

Fixes #331

### CODE REVIEW

**Comment by thecoolestguy** [comment]
Code checks out... Needs functional review.

**Comment by saschaben** [comment]
text entry field for notes is missing.
status should be editable.

**Comment by jrjohnson** [comment]
@saschaben  - status is editable by anyone?  It's in the learning_material table so a change will be a change for every connected session/course.

**Comment by saschaben** [comment]
@jrjohnson re status: right now status can only be changed by the "owner", but all too frequently the owner delegates management to someone else who needs to modify status, or departs and new ownership needs to be assigned. In the future we can work out a means of grabbing or reassigning ownership, but for now I think the simplest short term fix is allowing the status to be modified by all users -- until we can implement permissions controls.

**Comment by jrjohnson** [comment]
@saschaben - ready for testing again.  Status can now be edited.

**Pull request merged**
