### PR TITLE
Use ilios-common to provide dashboard

### PR DESCRIPTION
**Pull request by jrjohnson**
Ilios Common now holds code that is in both the frontend and iti-app applications.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit cf09209667ae527137a1e9abba52e547590bc7cc

https://deploy-preview-3048--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit d2dae96b92ee95e07d692e11d00984deac3235fa

https://deploy-preview-3048--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
School picker for "All Events" mode on calendar does not appear to be working....

**Comment by dartajax** [comment]
Not a huge deal but I noticed that when accessing the `Detail` filter, the outer right blue border is missing ...

image

But when accessing the `Course / Type`, it is present. This could be fixed after merging though. The rest of it looks good to me.

image

**Pull request merged**
