### PR TITLE
consolidate sequence block components

### PR DESCRIPTION
**Pull request by stopfstedt**
- [x] use page objects throughout
- [x] rolls the various editor sub-components for sequence block attributes into the overview components, these are one-offs that outlived their pre-octane-era usefulness

### CODE REVIEW

**Review by jrjohnson — APPROVED** [review]
👋

**Review by dartajax — CHANGES_REQUESTED** [review]
Button appearing where it should not be ...

image

**Comment by stopfstedt** [comment]
> Button appearing where it should not be ...

good find. fixed it, please re-review. thanks!

:heavy_check_mark:

**Review by dartajax — APPROVED** [review]
ein besserung - nice

**Pull request merged**
