### PR TITLE
For ILM Sessions give the due date as the first offering date

### LINKED ISSUE #84: ILM 'Due By' dates not displaying
ILM sessions are not displaying their due dates in the "first offering date" column. guessing we are not grabbing the ilm_session_facet_date value in the API somewhere.

### PR DESCRIPTION
**Pull request by jrjohnson**
Added dueDate and hours to ILM Session Model

Fixes #84

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/282" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
just to clarify -- are we simply injecting a faux date currently in place of due date for display? assuming so since all ILMs show 12am today for the due date. If not...check it out.

**Comment by jrjohnson** [comment]
Make sure you restart your ember server - I had to add the data since it wasn't in the original fixtures.

**Comment by saschaben** [comment]
I believe this needs to be reverted --- the ILM dates showing are always the value `currentDate (12:00:00am)`.

**Pull request merged**
