### PR TITLE
Remove underline option from froala editor

### LINKED ISSUE #1005: Remove Underline Button from Froala Editor
It doesn’t work since the `<U>underline this </U>`  tag that it utilizes is not in HTML anymore.

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #1005

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please review http://563a3d9371e20a368c00002d.ilios-frontend.netlify.com/ and approve.

**Comment by dartajax** [comment]
It looks good to me.

**Comment by dartajax** [comment]
:+1:

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
