### PR TITLE
added 'user disabled' icon to search result if applicable.

### LINKED ISSUE #1456: add 'disabled' icon to user search
fine. disabled icons are here:

selection_119

not fine. disabled icons are missing:

selection_120

add them to the search results list.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1456

### CODE REVIEW

**Comment by stopfstedt** [comment]
selection_126

**Comment by jrjohnson** [comment]
I think this needs some color as well.  Either the icon should be red or maybe the user could be grey.

**Comment by saschaben** [comment]
@stopfstedt @jrjohnson yes -- icon color should be red, to match usage elsewhere.

**Comment by stopfstedt** [comment]
good catch. fixed the color discrepancy.

**Pull request merged**
