### PR TITLE
Save offerings correctly

### LINKED ISSUE #901: Small Group Generator Fail
https://ilios3-demo.ucsf.edu/courses/773/sessions/22154

Using Prologue >> 15-16 ...

generator1

generator2

### PR DESCRIPTION
**Pull request by jrjohnson**
Aligned the offering with the API.  Along with some corresponding changes to the API this Fixes #901

### CODE REVIEW

**Comment by stopfstedt** [comment]
dig! :+1:

**Comment by stopfstedt** [comment]
homu +r

**Comment by stopfstedt** [comment]
@homu +r

**Comment by stopfstedt** [comment]
@homu r+

**Comment by jrjohnson** [comment]
@homu retry

**Comment by jrjohnson** [comment]
@homu r=stopfstedt

**Comment by jrjohnson** [comment]
:+1: trying a review star to see if that kicks of homy

**Pull request merged**
