### PR TITLE
Remove detail view css

### LINKED ISSUE #1705: Style cleanup and consolidation
Our styles as obviously not in great shape - such is life - lets try and find common components and apply consistent styles to these areas.
- [ ] Dashboard
- [x] Course List (#1791)
- [x] Course details (#1771)
- [x] Learner group list (#1791)
- [x] Learner group details (#2282)
- [x] instructor groups list (#1791)
- [x] instructor group details (#2360)
- [x] School List (#1791)
- [x] School Details (#2377)
- [x] Programs list (#1791)
- [x] Program details (#2575)
- [x] Program Year details (#2583)
- [x] Admin Dashboard (#1806)
- [x] Users List (#2718)
- [x] New user form
- [ ] Cohort Assignment list
- [ ] Pending user updates list
- [ ] Single user
- [ ] Curriculum inventory
- [ ] Session List
- [ ] Publish all sessions
- [ ] Print Course
- [ ] Session Publication check (#3135)

### PR DESCRIPTION
**Pull request by jrjohnson**
At long last and with great fanfare this removed the final pieces of our cascading (and difficult to manage) `.detail-view` CSS class.

Fixes #1705 

needs visual review of: 
- course print view
- "publish all sessions" dialog

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit e17c3aa645feefb5368cc1754a968eae6629baee

https://deploy-preview-3396--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
old bullet points ...

image

new bullet points ...

image

**Comment by dartajax** [comment]
There is a similar situation with Publish All. 

Before ...

image


After ...

image

**Comment by jrjohnson** [comment]
Thanks @dartajax / @stopfstedt. I fixed these issues and this is ready for review again.

**Comment by dartajax** [comment]
It looks much better. I am reviewing the Print Preview currently. I miss the border.

**Comment by dartajax** [comment]
Regarding Print Preview ...

The bullet points should maintain their indented nature.  

Before (with indentation in place) ...

image

In this PR ...

image

**Comment by jrjohnson** [comment]
Ok @dartajax please give this another look. I added the border back and fixed the list bullet points.

**Comment by dartajax** [comment]
LGTM 👍

**Pull request merged**
