### PR TITLE
replaced class on saved results container.

### PR DESCRIPTION
**Pull request by stopfstedt**
not perfect, but better.

refs #1948.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit cd36f3e5178f23c36486944fb4329ee6b0c8fa56

https://deploy-preview-2592--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
Hey @stopfstedt, where is this supposed to work?  On Instructor Group >> New >> Save, it looks like what @saschaben mentioned above.

**Comment by dartajax** [comment]
Follow up .. it looks nice in Courses >> New >> Save.  If we could do that everywhere, extra thumbs up.  Nice.

**Comment by dartajax** [comment]
`New Course` and `New Session` = nice.

**Pull request merged**
