### PR TITLE
added vocab/terms assignment controls.

### LINKED ISSUE #1318: Add Taxonomies to extend topic tags
See Ilios/Ilios#1257.

Extend the current topic manager to provide for additional complex taxonomies of tagging.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1318.

### CODE REVIEW

**Comment by stopfstedt** [comment]
@saschaben @jrjohnson this can be click tested at this point.

- [ ] assign/unassign terms to program year
- [ ] assign/unassign terms to course
- [ ] assign/unassign terms to session

i yanked topics from the calendar filtering controls and the myreport generator. please check that this didn't introduce any regressions in that area.

thanks!

todo for next week: 
- tooltips on terms.
- fix/complete test coverage

**Comment by saschaben** [comment]
all three action items look really good. add/remove to programs. add/remove to courses, add/remove to sessions all on track.

One thing --- if we can sneak in a collapser for the Competency section on program and course, the user experience would be much improved. Right now, because of the typical length of the competency list displayed, the page jumps significantly away from the focus area of Terms after saving in the manager. Collapsing competencies would reduce the page height of the display block, and in turn reduce the distance of the visual herkyjerky jump.

If that is more effort than seems reasonable to add into this, please create a followup ticket to address this as a new issue.

**Comment by stopfstedt** [comment]
ok, assuming that travis won't fail - this is ready for review. i gave up on covering the new components with integration tests - they just weren't jiving with the DS models at all. something to revisit some other time..

**Comment by jrjohnson** [comment]
Took at shot at reviewing the big changes lots of really good stuff here and I didn't see anything that I would change.  Needs a click through review and then it can be merged.

**Pull request merged**
