### PR TITLE
Relocate the Learner Group Calendar

### PR DESCRIPTION
**Pull request by jrjohnson**
Moving this up by it's toggle so it is instantly visible in groups with many members.

Fixes ilios/ilios#5616

### CODE REVIEW

**Review by stopfstedt — DISMISSED** [review]
LGTM

**Review by dartajax — CHANGES_REQUESTED** [review]
I hate to be that guy but a tidbit more vertical spacing would be nice just to move the calendar down a couple rows so the border line is not intermeshed with the button barriers - "Upload Group Assignments" "Manage" buttons ...

image

**Comment by jrjohnson** [comment]
Good catch @dartajax, this is ready for re-review now.

**Review by dartajax — APPROVED** [review]
I am fine with this. Thanks @jrjohnson for doing that adjustment - it looks cleaner.

**Pull request merged**
