### PR TITLE
added indentation to filter lists

### LINKED ISSUE #859: Filter Lists Need Proper Indentation
See the screenshot attached showing indentation of the lists ....

filterindent

Here's what we currently have ...

filternoindent

### PR DESCRIPTION
**Pull request by djvoa12**
screen shot 2015-10-26 at 6 56 40 pm

Fixes #859

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax please test and star this if it works for your ticket.

**Comment by dartajax** [comment]
Can you deploy a netlify or something for me to test?

**Comment by jrjohnson** [comment]
I searched slack - looks like this is it: http://562fc99671e20a62b500000e.ilios-frontend.netlify.com/

**Comment by dartajax** [comment]
Sorry @jrjohnson - I should have done a slack search myself - I was "slacking".

**Comment by dartajax** [comment]
That looks great - nice stuff.

**Comment by dartajax** [comment]
:+1:

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
