### PR TITLE
Test JSON:API Implementation

### PR DESCRIPTION
**Pull request by jrjohnson**
This is never intended to be merged, it's just a PR to cause a testing build with the JSON:API setup from common.

### CODE REVIEW

**Comment by saschaben** [comment]
course rollover: FAIL. Attempt to push the new course fails silently, no course is created, and user remains on original course page.

**Comment by saschaben** [comment]
CI report rollover: PARTIAL FAIL. on rollover of a report, system runs and returns a "success" banner, but action buttton continues to show spinner, and user is not returned automatically to report list page. on manual navigation back to list, new rolled over report does not appear until hard refresh.

**Comment by saschaben** [comment]
Add learner from cohort to learner group: FAIL.

```
VM308:1 PATCH https://ilios3-demo.ucsf.edu/api/v2/learnergroups/17218 500
(anonymous) @ VM308:1
eval @ trycatch.js:166
eval @ instrument.js:293
send @ jquery.js:10099
ajax @ jquery.js:9682
_ajaxRequest @ rest.js:937
_ajax @ rest.js:969
(anonymous) @ rest.js:927
initializePromise @ rsvp.js:520
Promise @ rsvp.js:1021
ajax @ rest.js:916
updateRecord @ json-api.js:228
(anonymous) @ -private.js:9645
invokeCallback @ rsvp.js:493
(anonymous) @ rsvp.js:558
(anonymous) @ rsvp.js:19
invokeWithOnError @ backburner.js:347
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
Backburner._boundAutorunEnd @ backburner.js:629
Promise.then (async)
iterations @ backburner.js:28
flush @ index.js:43
_scheduleAutorun @ backburner.js:1179
_end @ backburner.js:970
Backburner._boundAutorunEnd @ backburner.js:629
Promise.then (async)
iterations @ backburner.js:28
flush @ index.js:43
_scheduleAutorun @ backburner.js:1179
_ensureInstance @ backburner.js:1167
ensureInstance @ backburner.js:922
(anonymous) @ index.js:568
dirtyTagFor @ validator.js:518
markObjectAsDirty @ index.js:637
notifyPropertyChange @ index.js:675
arrayContentDidChange @ index.js:785
arrayContentDidChange @ array.js:611
flushCanonical @ -private.js:2964
retrieveLatest @ -private.js:3007
notifyHasManyChange @ -private.js:4667
_flushPendingManyArrayUpdates @ -private.js:6657
invoke @ backburner.js:338
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_run @ backburner.js:1015
_join @ backburner.js:989
join @ backburner.js:760
_scheduleManyArrayUpdate @ -private.js:6626
notifyHasManyChange @ -private.js:6704
notifyHasManyChange @ -private.js:1166
addRecordData @ -private.js:1025
(anonymous) @ -private.js:374
addRecordDatas @ -private.js:373
addToHasMany @ -private.js:1593
replace @ -private.js:2984
replaceContent @ array_proxy.js:164
replace @ array_proxy.js:146
replace @ index.js:830
insertAt @ array.js:93
pushObject @ array.js:1417
(anonymous) @ learner-group.js:346
addUserToGroupAndAllParents @ learner-group.js:344
async function (async)
addUserToGroupAndAllParents @ learner-group.js:343
addUserToGroup (task) @ learnergroup-summary.js:299
_resumeGenerator @ -task-instance.js:550
_handleResolvedContinueValue @ -task-instance.js:722
_proceed @ -task-instance.js:675
invokeWithOnError @ backburner.js:349
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_run @ backburner.js:1009
_join @ backburner.js:989
join @ backburner.js:760
join @ index.js:168
_proceedSoon @ -task-instance.js:631
proceed @ -task-instance.js:648
(anonymous) @ -task-instance.js:35
Promise.then (async)
handleYieldedUnknownThenable @ -task-instance.js:34
_handleYieldedValue @ -task-instance.js:757
_handleResolvedContinueValue @ -task-instance.js:734
_proceed @ -task-instance.js:675
invokeWithOnError @ backburner.js:349
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_run @ backburner.js:1009
_join @ backburner.js:989
join @ backburner.js:760
join @ index.js:168
_proceedSoon @ -task-instance.js:631
proceed @ -task-instance.js:648
(anonymous) @ -task-instance.js:35
Promise.then (async)
handleYieldedUnknownThenable @ -task-instance.js:34
_handleYieldedValue @ -task-instance.js:757
_handleResolvedContinueValue @ -task-instance.js:734
_proceed @ -task-instance.js:675
_scheduleProceed @ -task-instance.js:663
_start @ -task-instance.js:330
_startTaskInstance @ -scheduler.js:108
_flushQueues @ -scheduler.js:81
schedule @ -scheduler.js:63
_performShared @ -task-property.js:377
perform @ -task-property.js:347
(anonymous) @ -helpers.js:25
_join @ backburner.js:995
join @ backburner.js:760
join @ index.js:168
(anonymous) @ index.js:263
addSingleUser (task) @ learnergroup-cohort-user-manager.js:214
_resumeGenerator @ -task-instance.js:550
_handleResolvedContinueValue @ -task-instance.js:722
_proceed @ -task-instance.js:675
invokeWithOnError @ backburner.js:349
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_runExpiredTimers @ backburner.js:1097
sentryWrapped @ helpers.js:91
setTimeout (async)
eval @ trycatch.js:52
setTimeout @ backburner.js:50
_installTimerTimeout @ backburner.js:1157
_reinstallTimerTimeout @ backburner.js:1134
_later @ backburner.js:1045
later @ backburner.js:817
later @ index.js:408
__ec_yieldable__ @ utils.js:141
_invokeYieldable @ -task-instance.js:784
_handleYieldedValue @ -task-instance.js:755
_handleResolvedContinueValue @ -task-instance.js:734
_proceed @ -task-instance.js:675
_scheduleProceed @ -task-instance.js:663
_start @ -task-instance.js:330
_startTaskInstance @ -scheduler.js:108
_flushQueues @ -scheduler.js:81
schedule @ -scheduler.js:63
_performShared @ -task-property.js:377
perform @ -task-property.js:347
(anonymous) @ -helpers.js:25
_join @ backburner.js:995
join @ backburner.js:760
join @ index.js:168
(anonymous) @ index.js:263
trigger @ core_view.js:70
superWrapper @ index.js:424
_run @ backburner.js:1005
_join @ backburner.js:989
join @ backburner.js:760
join @ index.js:168
(anonymous) @ has_element.js:26
instrument @ index.js:144
handleEvent @ has_element.js:22
handleEvent @ view_support.js:369
(anonymous) @ event_dispatcher.js:332
dispatch @ jquery.js:5429
elemData.handle @ jquery.js:5233
sentryWrapped @ helpers.js:91
Show 72 more frames
instrument.js:147 ErrorClass {isAdapterError: true, stack: "Error: Ember Data Request PATCH https://ilios3-dem…de_modules/@sentry/browser/esm/helpers.js?:91:17)", description: undefined, fileName: undefined, lineNumber: undefined, …}```

**Comment by saschaben** [comment]
Remove learner from group: FAIL.
```
VM308:1 PATCH https://ilios3-demo.ucsf.edu/api/v2/learnergroups/17257 500
(anonymous) @ VM308:1
eval @ trycatch.js:166
eval @ instrument.js:293
send @ jquery.js:10099
ajax @ jquery.js:9682
_ajaxRequest @ rest.js:937
_ajax @ rest.js:969
(anonymous) @ rest.js:927
initializePromise @ rsvp.js:520
Promise @ rsvp.js:1021
ajax @ rest.js:916
updateRecord @ json-api.js:228
(anonymous) @ -private.js:9645
invokeCallback @ rsvp.js:493
(anonymous) @ rsvp.js:558
(anonymous) @ rsvp.js:19
invokeWithOnError @ backburner.js:347
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
Backburner._boundAutorunEnd @ backburner.js:629
Promise.then (async)
iterations @ backburner.js:28
flush @ index.js:43
_scheduleAutorun @ backburner.js:1179
_end @ backburner.js:970
Backburner._boundAutorunEnd @ backburner.js:629
Promise.then (async)
iterations @ backburner.js:28
flush @ index.js:43
_scheduleAutorun @ backburner.js:1179
_ensureInstance @ backburner.js:1167
ensureInstance @ backburner.js:922
(anonymous) @ index.js:568
dirtyTagFor @ validator.js:518
markObjectAsDirty @ index.js:637
notifyPropertyChange @ index.js:675
arrayContentDidChange @ index.js:785
arrayContentDidChange @ array.js:611
flushCanonical @ -private.js:2964
retrieveLatest @ -private.js:3007
notifyHasManyChange @ -private.js:4667
_flushPendingManyArrayUpdates @ -private.js:6657
invoke @ backburner.js:338
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_run @ backburner.js:1015
_join @ backburner.js:989
join @ backburner.js:760
_scheduleManyArrayUpdate @ -private.js:6626
notifyHasManyChange @ -private.js:6704
notifyHasManyChange @ -private.js:1166
removeRecordDataFromOwn @ -private.js:1100
removeRecordData @ -private.js:488
(anonymous) @ -private.js:369
removeRecordDatas @ -private.js:369
removeFromHasMany @ -private.js:1598
replace @ -private.js:2979
replaceContent @ array_proxy.js:164
replace @ array_proxy.js:146
replace @ index.js:830
removeAt @ array.js:87
removeAt @ array.js:1400
removeObject @ array.js:1581
(anonymous) @ learner-group.js:326
removeUserFromGroupAndAllDescendants @ learner-group.js:324
async function (async)
removeUserFromGroupAndAllDescendants @ learner-group.js:323
removeUserToCohort (task) @ learnergroup-summary.js:307
_resumeGenerator @ -task-instance.js:550
_handleResolvedContinueValue @ -task-instance.js:722
_proceed @ -task-instance.js:675
invokeWithOnError @ backburner.js:349
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_run @ backburner.js:1009
_join @ backburner.js:989
join @ backburner.js:760
join @ index.js:168
_proceedSoon @ -task-instance.js:631
proceed @ -task-instance.js:648
(anonymous) @ -task-instance.js:35
Promise.then (async)
handleYieldedUnknownThenable @ -task-instance.js:34
_handleYieldedValue @ -task-instance.js:757
_handleResolvedContinueValue @ -task-instance.js:734
_proceed @ -task-instance.js:675
_scheduleProceed @ -task-instance.js:663
_start @ -task-instance.js:330
_startTaskInstance @ -scheduler.js:108
_flushQueues @ -scheduler.js:81
schedule @ -scheduler.js:63
_performShared @ -task-property.js:377
perform @ -task-property.js:347
(anonymous) @ -helpers.js:25
_join @ backburner.js:995
join @ backburner.js:760
join @ index.js:168
(anonymous) @ index.js:263
removeSingleUser (task) @ learnergroup-user-manager.js:356
_resumeGenerator @ -task-instance.js:550
_handleResolvedContinueValue @ -task-instance.js:722
_proceed @ -task-instance.js:675
invokeWithOnError @ backburner.js:349
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:960
end @ backburner.js:710
_runExpiredTimers @ backburner.js:1097
sentryWrapped @ helpers.js:91
setTimeout (async)
eval @ trycatch.js:52
setTimeout @ backburner.js:50
_installTimerTimeout @ backburner.js:1157
_reinstallTimerTimeout @ backburner.js:1134
_later @ backburner.js:1045
later @ backburner.js:817
later @ index.js:408
__ec_yieldable__ @ utils.js:141
_invokeYieldable @ -task-instance.js:784
_handleYieldedValue @ -task-instance.js:755
_handleResolvedContinueValue @ -task-instance.js:734
_proceed @ -task-instance.js:675
_scheduleProceed @ -task-instance.js:663
_start @ -task-instance.js:330
_startTaskInstance @ -scheduler.js:108
_flushQueues @ -scheduler.js:81
schedule @ -scheduler.js:63
_performShared @ -task-property.js:377
perform @ -task-property.js:347
(anonymous) @ -helpers.js:25
_join @ backburner.js:995
join @ backburner.js:760
join @ index.js:168
(anonymous) @ index.js:263
trigger @ core_view.js:70
superWrapper @ index.js:424
_run @ backburner.js:1005
_join @ backburner.js:989
join @ backburner.js:760
join @ index.js:168
(anonymous) @ has_element.js:26
instrument @ index.js:144
handleEvent @ has_element.js:22
handleEvent @ view_support.js:369
(anonymous) @ event_dispatcher.js:332
dispatch @ jquery.js:5429
elemData.handle @ jquery.js:5233
sentryWrapped @ helpers.js:91
Show 74 more frames
instrument.js:147 ErrorClass {isAdapterError: true, stack: "Error: Ember Data Request PATCH https://ilios3-dem…de_modules/@sentry/browser/esm/helpers.js?:91:17)", description: undefined, fileName: undefined, lineNumber: undefined, …}
```

**Comment by saschaben** [comment]
It seems like all PATCH actions are failing here....

**Comment by jrjohnson** [comment]
I believe I've addressed all these issues (they had a single source). Testing is ready to resume again.

**Comment by jrjohnson** [comment]
Both course and CI rollover should now be working (and can be tested again).

**Comment by dartajax** [comment]
Correct selection of future year rollover - FAIL

I was doing a rollover into a future year that probably shouldn't even be available since there is no cohort yet -- 2022-23 for example -- I tried it on demo3 and on this PR. The PR screen shot is shown below. I believe there is an inconsistency in both versions but bear with me. Tediousness will abound.

From PR version - this version ...

image

From demo3 - same procedure and process ...

image

**Comment by jrjohnson** [comment]
Founds some issues with dates that have now been resolved. @dartajax this should fix your rollover issues, but please test again to be sure.

**Comment by dartajax** [comment]
As far as the date selection process is concerned for the start date / day, that has been resolved.
Also, the future year business that was failing before appears to be fine - same as demo3 was before.

**Pull request closed without merging**
