### PR TITLE
Use an addon for the action menu

### PR DESCRIPTION
**Pull request by jrjohnson**
Replaces action menu across the board with one that actually works.  Once this is merged #46 should be assigned to @jenzweben to take a look at style specifics.

### CODE REVIEW

**Comment by saschaben** [comment]
seems to be just fine in groups, but is acting oddly in sessions (perhaps due to only one selection option being available?)

**Comment by saschaben** [comment]
Hmm. this widget definitely wonky as implemented in course list course and session list. NRFPT.

**Comment by jrjohnson** [comment]
Can you specify wonky.  Works for me, so I need some more specifics.

**Comment by saschaben** [comment]
click the widget, make selection from dropdown: lable from dropdown prints to the widget form, and no action occurs. I'd give you a screenshot, but the branch is now giving me a handlebars error and won't render the page...

**Comment by saschaben** [comment]
Uncaught Error: <ilios@component:action-menu::ember4504> Handlebars error: Could not find property 'rl-dropdown-container' on object <ilios@component:action-menu::ember4504>.

**Comment by jrjohnson** [comment]
Thanks.  Use nomless to fix that error.  I will look into the click action.  Not sure if I tested that there.

**Comment by saschaben** [comment]
ilios 2015-02-10 13-01-11
ilios 2015-02-10 13-01-59

**Comment by jrjohnson** [comment]
ok @saschaben give this another look.

**Comment by saschaben** [comment]
much better for course list, group list, and course overview. still has a z-index issue where the dropdown gets hidden when at the bottom of a content area:

ilios 2015-02-10 15-08-32

...and still is wonky per before on sessions list. FYI this is acceptable for demo, but I don't want any code inconsistencies to slip thru the cracks.

**Comment by jrjohnson** [comment]
Session list is broken because it doesn't actually do anything.  I'm going to pass off the z-index problem to @jenzweben for after this is merged and she takes a styling pass.

**Pull request merged**
