### PR TITLE
show more scope notes

### LINKED ISSUE #939: show more of  MeSH scope notes in picker.
based on https://github.com/ilios/frontend/pull/919#issuecomment-150483407:

truncate scope notes in the MeSH picker at the 250 char limit.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #939

### CODE REVIEW

**Comment by stopfstedt** [comment]
@jrjohnson I added new, computed properties to the mesh-concept model. these feel/look kinda gross. any better idea as how to handle this? thx.

**Comment by saschaben** [comment]
user side of things here looks good.

**Comment by jrjohnson** [comment]
:+1: via Sascha.  @homu r+

**Comment by jrjohnson** [comment]
@stopfstedt scsslint is failing here:
`app/styles/components/_mesh-manager.scss:17 [W] QualifyingElement: Avoid qualifying class selectors with an element.`

**Comment by jrjohnson** [comment]
:+1: no functional changes since last review.  
@homu r+

**Pull request merged**
