### PR TITLE
raised course query filter limit

### LINKED ISSUE #1064: "filter by course" list incorrect
the calendar filter for course is not accurately displaying the available courses for a given year:

CASE: 
1. go to courses & sessions. list courses for medicine 2015-16.
2. search for Foundations of Patient Care Year 1 (FPC1). Note publish status.
3. return to dashboard.
4. open calendar and turn on filters
5. flip to filter by course
6. select year 2015-16.
7. scroll thru the courses listed for filtering. you will not find FPC1

For any selected year, the filter course list should reflect:
* for a non-student: all courses for that year regardless of publish status
* for a student, all courses for that year with a status of published or scheduled.

Assigning this to @djvoa12 initially only because he has had his head under the hood of filters recently. If needed please reassign the @jrjohnson.

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #1064 

New limit is `1000`

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben what do you think the absolute maximum number of courses that might be attached to a program year might be?  Is 200 sufficient?  Or should we make it 1000?

**Comment by saschaben** [comment]
We should probably raise it, but not to 1000. 300 should be ample.

**Comment by jrjohnson** [comment]
I should have mentioned that there is no cost to picking a number that is too high.  We're shooting for all of the results.  So 10000 is not more expensive than 10 unless you actually have 10000 in which case I guess you would still want them all - but probably be calling Dave to add paging to the list.

**Comment by saschaben** [comment]
1000 is a big scary number. but I guess if this is a no-cost no-fault thing then that's fine. I can't actually conceive of a curriculum with more than a few hundred courses listed in a year, but hey.

**Comment by saschaben** [comment]
:+1:

**Comment by djvoa12** [comment]
New limit = 1000

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
