### PR TITLE
Learner Group Inprovements

### PR DESCRIPTION
**Pull request by jrjohnson**
Addressed a few simple pieces of #1506 before tackling a larger refactoring.

Added breadcrumbs to the top of the page.

Added a title attribute with email and campusId in it to make it easier
to figure out which user was which when there are duplicate names in a
cohort.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please take a look.  Since addressing the large set of issues in learner groups is going to take a bit more time I figured we should get these things in for this weeks release.

**Comment by saschaben** [comment]
@jrjohnson good call. I think this looks fine for now -- we can pump up styling with the larger revamp. two quickies though: 
1) If it is possible to quickly plug in a `0.5em margin-left` value for the `.breadcrumb` style div, that would make it a bit more visually balanced until then, but if it mucks up our other placements in the app then it can stay as is.
2) Again, if possible: Let's add a pipe with some spacing as delimiter in the tooltip to help clean that up: `Yakko.Warner@example.edu  |  xxx666872` rather than `Yakko.Warner@example.edu xxx666872`

That should do it for a first step we can release on friday.

**Comment by jrjohnson** [comment]
I can add the margin but it will move the one on vocabularies as well.  Is that OK?

**Comment by saschaben** [comment]
Just validated that the margin shift won't adversely affect display in vocabs. go for it.

**Pull request merged**
