### PR TITLE
Adds input controls for learner group url

### PR DESCRIPTION
**Pull request by stopfstedt**
Selection_169

fixes https://github.com/ilios/frontend/issues/5563

### CODE REVIEW

**Review by jrjohnson — APPROVED** [review]

**Comment by saschaben** [comment]
Looks like the input form field is not auto-refreshing to text after hitting the green check to save; a click out of the form field allows the form input to refresh to text link.

**Comment by stopfstedt** [comment]
> Looks like the input form field is not auto-refreshing to text after hitting the green check to save; a click out of the form field allows the form input to refresh to text link.

good find, although caused by something different. turns out that the old form validations library (`ember-cp-validations`) we're still using here is accepting URLs without protocol, but the backend is rejecting this. weak!

Selection_165

will see if i can configure us out of this calamity, and if that doesn't work then check into other options.

**Comment by stopfstedt** [comment]
i'll need to octanify this component b/c of the flaw in the currently used validation library.

**Comment by stopfstedt** [comment]
needs re-review and regression testing.

**Comment by stopfstedt** [comment]
Selection_170

the link validation issue has been fixed.

**Review by jrjohnson — APPROVED** [review]

**Comment by saschaben** [comment]
ok. the spinner issue with user management is noted. we should clean that up someday.

On point though: If we are going to require fully formed urls with protocols explicitly entered, we need to provide that information in the validation prompt, eg. "`a valid url is required ('https://mysmellysocks.com')`", or provide the pre-filled "`https://`" prompt in the form field as we do with learning materials. Otherwise it's a little confusing (if it confused me, it's guaranteed to confuse users when they plug in "www.thisplace.com" and they cannot save).

**Comment by stopfstedt** [comment]
> ok. the spinner issue with user management is noted. we should clean that up someday.
> 
> On point though: If we are going to require fully formed urls with protocols explicitly entered, we need to provide that information in the validation prompt, eg. "`a valid url is required ('https://mysmellysocks.com')`", or provide the pre-filled "`https://`" prompt in the form field as we do with learning materials. Otherwise it's a little confusing (if it confused me, it's guaranteed to confuse users when they plug in "www.thisplace.com" and they cannot save).

fair point. i'm going to pre-fill with `https://` then, as we do with URLs in the offering form. 
Selection_177

**Comment by saschaben** [comment]
FTW!

**Pull request merged**
