### PR TITLE
Add language picker to user menu

### PR DESCRIPTION
**Pull request by jrjohnson**
Also added a test to ensure translation files stay in sync

### CODE REVIEW

**Comment by saschaben** [comment]
Hmm. this is failing for me locally: it can't load the select list. throws error on line 16 of ilios-header.js    
> `return this.get('i18n.locales').map(function (locale) {`

with a `Uncaught TypeError: Cannot read property 'map' of undefined`...

**Comment by saschaben** [comment]
NB: requires nommore.

**Comment by dartajax** [comment]
I got the picker to work and the language does change but the menu items >> Dashboard >> Course & Sessions >> Learner Groups >> Instructor Groups >> Programs don't reflect the language change.  Dashboard at the top doesn't change either.

**Comment by jrjohnson** [comment]
I fixed the navigation and the titles.  Getting dates in the calendar recomputed is going to be a bit harder and required work with some other upstream modules.  I created #781 for this.

**Comment by saschaben** [comment]
looks great.

**Comment by thecoolestguy** [comment]
I also needed to nommore, but works/looks great once I did!

**Pull request merged**
