### PR TITLE
Improve click-choice-buttons

### LINKED ISSUE #2871: Refactor click-choice-buttons
These are using a jQuery selector and an asynchronous syntax that is blocking tests for #2869 - they also don't match the style on the rest of the site and should get some attention.

### PR DESCRIPTION
**Pull request by jrjohnson**
1) Refactor click-choice-buttons component
Makes it a bit more idiomatic in not using jQuery to set the state and
calling the passed action as a method.

2) 	Improve style for click-choice-buttons component
This matches better with the overall application look

The change should be tested on:
- [x] New User (student / staff toggle)
- [x] Learner groups new sub groups: (single / multiple toggle)
- [x] New Offering (single / small group toggle)

New buttons looks like: 
first

second

Fixes #2871

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit ca8f6f0e7387c3a0a72159a236ae2393e0c18f4b

https://deploy-preview-2872--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
not sure if you have seen, but the new buttons fail for offering creation when switching selection from small group to offering:
ilios courses and sessions 2017-04-16 22-30-30

NB: before QA and merge of this PR, please list here the inventory of locations where this component is deployed, this will allow for thorough review.

**Comment by jrjohnson** [comment]
Good catch on offerings - I hadn't gotten around to validating everything - just wanted to check the new style.  The change is reflected on:
New User (student / staff toggle)
Learner groups new sub gropus: (single / multiple toggle)
New Offering (single / small group toggle)

All should be working now.

**Comment by dartajax** [comment]
I tested the three locations above and it looks good.

**Comment by jrjohnson** [comment]
@gboushey ready for code review and merging.

**Pull request merged**
