### PR TITLE
Make links to dashboard courses permissions based

### LINKED ISSUE #983: Student view of dashboard should not include link to Courses
See title for information.

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #983

### CODE REVIEW

**Comment by saschaben** [comment]
well....hard to test without a pure student account, but with demo student instructor accounts 1 & 3, my courses loads without links, and then barfs up two 500 server errors. Assume we have a permissions issue on one or more courses being loaded....

**Comment by jrjohnson** [comment]
I was testing with demo_student1 I think.

**Comment by saschaben** [comment]
demo_student1-4 don't appear to have any events associated; My Courses just hangs on load. further investigation now...

**Comment by saschaben** [comment]
My Courses hangs on load for student with/without assignments to courses:

hangs

**Comment by saschaben** [comment]
demo student 1 continues to get links in "My Courses"

**Comment by saschaben** [comment]
references #779.

**Comment by jrjohnson** [comment]
:+1: 
@thecoolestguy this just needs code review,  I rebased and the other issues with timing are documented elsewhere.

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
