### PR TITLE
Align CI report list icons

### LINKED ISSUE #1978: Action Icons on CI Not Arranged Well
They should be arranged in a line, non?

image

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #1978
Supersedes #1984

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please review.  I took all the spacing away from the icons because adding more caused them to break lines again.  Is this ok?

**Comment by saschaben** [comment]
@jrjohnson 
hmm. I’m concerned about the closeness here. having a delete action sandwiched between to other content actions with little or no padding is a recipe for disaster

**Comment by jrjohnson** [comment]
Delete does have a confirmation.  I understand the issue though.  Would it make sense to put delete last and give it some space?  There isn't a lot of space to give, but I can give a little bit.

**Comment by saschaben** [comment]
if we put delete last, and can cram back in the 7px right-margin on the icon in the middle, that will work. I'd rather have them evenly spaced but I just want to get this stuff out the door.

**Comment by jrjohnson** [comment]
@saschaben updated, test again if you please.

**Comment by saschaben** [comment]
👍

**Pull request merged**
