### PR TITLE
Cache index.html with a service worker

### PR DESCRIPTION
**Pull request by jrjohnson**
This brings us several steps closer to offline support, but more importantly it avoids a network request when visiting the app which will speed up initial rendering.

Includes a modified error page that notices if a user is offline and replaces all error data with an offline message since errors are almost certainly coming from that anyway.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit bfe3722cc9aef35f2576f1c3daf38f5b77f714fd

https://deploy-preview-3245--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
Here's what happens with a hard refresh when not on the network. The Ilios flyout menu appears to be trying to load. 

image

**Comment by jrjohnson** [comment]
@dartajax what do you think we should do about that? It *is* loading, but it will never finish with no connection. I can sort of see some options, but I'm wondering what you see as the best way to handle that?

**Comment by dartajax** [comment]
I don't have a problem with the way that happened. I just wanted to point it out. I'm going to merge this - it looks good.

**Pull request merged**
