### PR TITLE
Improve My Reports

### LINKED ISSUE #1238: MyReports has some issues
- [x] "__All session types for instructor [X]__" returns `_this[mapper] is not a function`
- [x] "__All session types for Competency [X]__" returns `t[n] is not a function`
- [ ] "__All sessions for course [X]__"  returns `500: Error: Adapter operation failed ` when attempting to retrieve list of courses
- [x] For reports requiring a predicate selection (like "all courses associated to topic which is [X]"), the select list of predicates does not allow for selection of the default selected display value (topic: acute  care, for instance) -- only an active select action will allow a save.
- [x] "__All session types associated to__"....association list is incorrect. should be: 
 - COURSE 
 - PROGRAM YEAR 
 - PROGRAM 
 - INSTRUCTOR 
 - INSTRUCTOR GROUP 
 - LEARNING MATERIAL 
 - COMPETENCY 
 - MESH TERM 
 - TOPIC 
- Currently list includes 
 - SESSION 
 - INSTRUCTOR 
 - INSTRUCTOR GROUP 
 - COMPETENCY 
 - MESH TERM

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixed reports which return a session type.
Added correct options for session type prepositional objects.
Fixed an issue where the users would have to pick something from the object list, the default option would not save.

Fixes #1238

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please review - original ticket has notes on what didn't get fixed.

**Comment by saschaben** [comment]
Round one test results. I've excluded all calls to "All Courses":
1. All `session types` Associated with [X]; [X] should not include `SESSION`. Please remove.
2. All [X] Associated with `Session` throws 500 error.
3. All Instructor Group for Session Type throws 500 error.
4. All learning material for session type throws 500 error.
5. all competency for session type throws 500 error.
6. all topic for session type throws 500 error.
7. all mesh for session type throws 500 error.
8. all session type for program throws 500 error.
9. all session type for learning material X throws 500 error.
10. all session type for course X throws 500 error.

round two to follow.

**Comment by saschaben** [comment]
Round two:

1. all instructor for course X throws 500 error.
2. all instructor for session type X throws 500 error.
3. all instructor for topic X throws 500 error.
4. all instructor for learning material X throws 500 error.
5. all instructor for course X throws 500 error.
6. all instructor groups for session type X throws 500 error.

**Comment by jrjohnson** [comment]
@saschaben There was a really big bug affecting any report with a prepositional object, honestly I'm not sure how any of them ever ran.  I just pushed a fix, I'm guessing that most of these cases are now resolved.  Can you check?

**Comment by saschaben** [comment]
The following built reports still throw 500 errors proxied to demo:

-  All session type for Curriculum Ambassadors Program in Medicine (all session type for program)
-  All session type for Evidence-based medicine: what it is and what it isn't in Medicine	(all session type for learning material)
 - All topic for Boundaries and Priorities in Medicine	(all topic for competency) — no error, but slow
 - All instructor for Kaiser Family Foundation Health Reform Timeline in Medicine	(all instructor for learning material)
 - All instructor for Acute Care in Medicine (all instructor for topic)
 - All instructor for Lecture in Medicine	(all instructor for session type)
 - All session for Brain, Mind, and Behavior 2015-16 in Medicine	(all session for course)
 - All session type for Brain, Mind, and Behavior 2014-15 in Medicine (all session type for course)

**Comment by jrjohnson** [comment]
Nothing to really do to fix topic by competency.  It is just a very large number of table joins needed to get between a topic and a session / course / program year and then up the chain of objectives to the competency.

**Comment by jrjohnson** [comment]
@saschaben ready for another round of testing.  I added API tickets for some of these where we need a new filter on the sessionType.

**Comment by saschaben** [comment]
here's the final report failure list. I believe we now match expected outcomes (barring the last two anomalous actions)

reports that fail on load with 500 error:
- all session type for topic
- all session type for mesh
- all session type for learning material
- all session type for program
- all session type for course
- all instructors for course

reports that return a 500 error on build:
- all mesh term associated to session - blows up on build
- all topic associated to session - blows up on build
- all competency associated to session - blows up on build
- all LMs associated to session - blows up on build
- all instructor groups associated to session - blows up on build
- all instructors associated to session - blows up on build
- all program years associated to session - blows up on build
- all courses associated to session - blows up on build

weirdness:
- all programs associated to session - does NOT blow up on build
- all program associated to course - blows up on build 1 out of 4 times

**Comment by jrjohnson** [comment]
Ok - I'm good with merging with this list.  First block are all getting fixed on the API.  Second and third block is all about memory requirements which is low on demo and we have tickets in on the API side to make these more reliable.

**Pull request merged**
