### PR TITLE
set max length of offering room input to 60 char.

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #1398

### CODE REVIEW

**Comment by stopfstedt** [comment]
selection_094

**Comment by stopfstedt** [comment]
@jrjohnson please review and let me know if i'm on the right track.

not very happy right now with the inability to manually interpolate values into flash messages. 
also, the validation-error to flash message assignment feels kinda kludgy. `Ember.keys()` on validation errors object does not recurse into nested objects, therefore i had to alias nested component props to pull them up.

thoughts/ideas?

**Comment by jrjohnson** [comment]
Hmmm.... I don't love this and I'm not sure we are really getting anything from the validators library that we couldn't easily do on our own.  In fact this component actually has a couple of other validations happening that are not using the validators - they just spit out flash messages, which we could the translate more effectively.  I'm wondering if we should just pull out the small implementations we have of this and go with writing custom case specific validations and messages in each case.  That would probably give us a better UX for errors and I think the code would possible by cleaner as well.

As a side note I'm not super happy with the maintenance of ember-validators by dockyard.  They may be too busy to keep it up to date.

**Comment by saschaben** [comment]
FR: `Nom de l'emplacement est trop long (max. 60 caractères)`

**Comment by stopfstedt** [comment]
ok. thanks for the feedback. i hope this is 'good enough' for now. moving on...

**Comment by jrjohnson** [comment]
Yea, I'm ok with that.  @saschaben can you validate the UX and merge - the code looks good.

**Pull request merged**
