### PR TITLE
Added My Reports to Dashboard

### LINKED ISSUE #747: Add Reports Generation tools component to Dashboard
The new rendition of "My Reports". Please see #206 for additional details.

### PR DESCRIPTION
**Pull request by jrjohnson**
This is in pretty good functional shape.  Reports can be created and results can be viewed.  Everything needs some styling I think and the results can’t be clicked yet.

@saschaben please review the functionality and let me know where the gaps are.  Also make sure I read the matrix of options correctly.  I only implemented the white ones, not the under-review grey boxes.  If this works then we can figure out how much polish it needs before it is merged.

WIP: still needs translations
Requires ilios/ilios#1105 to be able to add new reports

Fixes #747

### CODE REVIEW

**Comment by saschaben** [comment]
Subject list: 
- [ ] includes session type (but displays as `missing translation) -- this is fine, but isn't included in 2.4

PO Lists: 
- [ ] default to the self-reference of the subject. This is verboten. But I know why you did this. Let's evaluate simple default options. Topics may be the key.
- [ ] Session Type is missing for the subject selections Session, Instructor, Instructor Group, Learning Material, Competency, Topic, and MeSH Term. 
- [ ] Instructor Group is missing for the subject selection "Instructor"
- [ ] Learning Material, , Competency, MeSH Term, and Session Type missing from subject selection "Topic"
- [ ] Program Year is not displaying any values.

Other:
- [ ] Until a PO selection is made, disallow the running of a report with the subject "Instructor" or "MeSH Term" (ie, "get all instructors in Ilios" or "return all MeSH terms")

Assuming save isn't yet supposed to work, as it returns a 400:

`code: 400, message: "Validation Failed",…}`
`code: 400`
`errors: {errors: ["This form should not contain extra fields."],…}`
`children: {title: [], subject: [], prepositionalObject: [], user: []}`
`errors: ["This form should not contain extra fields."]`
`message: "Validation Failed"`

**Comment by jrjohnson** [comment]
I'm going to have to drop programYear as a possible object for reports.  Its too complicated given our short time frame.  #1090 covers this.

**Comment by jrjohnson** [comment]
@saschaben please review again.  Note that you should now be able to create new reports against a local API (not against demo until we update).  However it turns out that reports were not working before - I fixed the frontend problem, but exposed some issues with filtering on the API that we will have to deal with before several of the reports will actually run.  We maybe be able to hack around this.

I think I fixed the issues noted above and also introduced a new report creation flow.  Let me know if it is a terrible idea.

**Comment by saschaben** [comment]
as much as I want to be testing this, I am unable to set up a local API instance. My vagrant setup needs to be completely rebuilt.  In the meanwhile:

* New report creation flow is great. Needs some formatting cleanup, but UX wise this is an improvement and a problem solver.
* Course selection in PO is missing a translation value (`missing translation:general.course`)
* minor quibble: don't think we need a report that gets all session types associated with a particular session.

I think that's it on the flow.

**Comment by saschaben** [comment]
One more thing: created reports must have a delete control. otherwise they will get out of hand quickly.

**Comment by saschaben** [comment]
On layout: better vertical spacing between the select fields is needed: using `<p>` instead of `<br>` would do...

**Comment by jrjohnson** [comment]
@saschaben / @dartajax  please translate (sorry for so many, I needed singular form of a bunch of common words.

```
'all': 'All',
'anything': 'Anything',
'competency': 'Competency',
'course': 'Course',
'topic': 'Topic',
'meshTerm': 'MeSH Term',
'sessionType': 'Session Type',
'programYear': 'Program Year',
'learningMaterial': 'Learning Material',
'optional': "Optional",
'instructor': 'Instructor',
'instructorGroup': 'Instructor Group',
'myReports': 'My Reports',
'newReport': 'New Report',
'reportTitle': 'Report Title',
'reportDisplayTitleWithObject': 'All {{subject}} for {{object}}',
'reportDisplayTitleWithoutObject': 'All {{subject}}',
'associatedWith': 'Associated with',
'whichIs': 'which is',
'reportMissingMeshTerm': 'MeSH Term is Required',
'reportMissingInstructor': 'Instructor is Required',
'reportMissingObjectForInstructor': 'Association is required when Instructor is the subject',
'reportMissingObjectForMeshTerm': 'Association is required when MeSH Term is the subject',
'allReports': 'All Reports',
```

**Comment by saschaben** [comment]
Fr:

'all': 'tous',
'anything': 'quelque chose',
'competency': 'compétence',
'course': 'cours',
'topic': 'sujet',
'meshTerm': 'terme de MeSH',
'sessionType': 'type de séance',
'programYear': 'année de diplôme',
'learningMaterial': 'matière d'étude',
'optional': "facultatif",
'instructor': 'Instructeur',
'instructorGroup': 'groupe des Instructeurs',
'myReports': 'mes rapports',
'newReport': 'nouveau rapport',
'reportTitle': 'titre du rapport',
'reportDisplayTitleWithObject': 'tous {{subject}} pour {{object}}',
'reportDisplayTitleWithoutObject': 'tous {{subject}}',
'associatedWith': 'associée de',
'whichIs': 'qui est',
'reportMissingMeshTerm': 'terme de MeSH requis',
'reportMissingInstructor': 'Instructeur requis',
'reportMissingObjectForInstructor': 'connexion requis quand <<instructeur>> est le sujet',
'reportMissingObjectForMeshTerm': 'connexion requis quand <<terme de MeSH>> est le sujet',
'allReports': 'tous rapports',

**Comment by dartajax** [comment]
'all': 'todo',
'anything': 'caulquier cosa',
'competency': 'competencia',
'course': 'curso',
'topic': 'tema',
'meshTerm': 'término de MeSH',
'sessionType': 'tipo de sesión',
'programYear': 'año de programa',
'learningMaterial': 'material de aprendizaje',
'optional': 'opcional',
'instructor': 'instructor',
'instructorGroup': 'grupo de instructores',
'myReports': 'mis reportes',
'newReport': 'nuevo reporte',
'reportTitle': 'título de reporte',
'reportDisplayTitleWithObject': 'todos {{subject}} para {{object}}',
'reportDisplayTitleWithoutObject': 'todos {{subject}}',
'associatedWith': 'asociado con',
'whichIs': 'cuál es',
'reportMissingMeshTerm': 'término de MeSH es necesario',
'reportMissingInstructor': 'instructor es necesario',
'reportMissingObjectForInstructor': 'asociación es necesario cuando instructor es el sujeto',
'reportMissingObjectForMeshTerm': 'asociación es necesario cuando término de MeSH es el sujeto',
'allReports': 'todos reportes',

**Comment by saschaben** [comment]
:+1:

**Comment by saschaben** [comment]
@thecoolestguy please review code and if passing muster, merge.

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
