### PR TITLE
realigns capabilities checks for single user group removal/assignment…

### PR DESCRIPTION
**Pull request by stopfstedt**
… with bulk removal/assignment checks.

fixes https://github.com/ilios/ilios/issues/4751

### CODE REVIEW

**Review by jrjohnson — APPROVED** [review]
I'm good with this change, but does the current user need to be root to do this action? I think maybe anyone who is allowed to edit should be able to do this because the core issue is that the learner group isn't disabled, just one of the members who now needs to be removed.

**Comment by stopfstedt** [comment]
> I'm good with this change, but does the current user need to be root to do this action? I think maybe anyone who is allowed to edit should be able to do this because the core issue is that the learner group isn't disabled, just one of the members who now needs to be removed.

i'll have a look at the extraneous is-root-user check, perhaps this can be removed.

**Comment by stopfstedt** [comment]
@jrjohnson - i removed the checks that were prohibiting _non-root users with learner-group edit permissions_  from adding/removing inactive users to/from learner groups.

@dartajax please take note on this.

**Comment by dartajax** [comment]
I think this is a great change/update. @dartajax = noted. Do you want this merged?

**Comment by stopfstedt** [comment]
> I think this is a great change/update. @dartajax = noted. Do you want this merged?

thanks @dartajax. let's run it by @saschaben  in the meeting today, I'd want him to sign off on this.

**Comment by stopfstedt** [comment]
this issue was discussed in today's Ilios team meeting - Sascha signed off on this change.

**Pull request merged**
