### PR TITLE
Create a higher order component for charts

### PR DESCRIPTION
**Pull request by jrjohnson**
By building the chart inside of a component we can be more in control of
the tooltip and we give our selves more headroom for easy API expansion
in the future.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit d037d3afe58281dd5c53708000a83f82823004f8

https://deploy-preview-2867--ilios-frontend.netlify.com

**Comment by gabycampagna** [comment]
Should changes be made to the chart-pie.js file as well and the donut chart? When testing donut chart hover state I am getting duplicated tooltips: 
screen shot 2017-04-14 at 11 59 04 am

Also saw this error: 
screen shot 2017-04-14 at 11 49 08 am

**Comment by jrjohnson** [comment]
Wow.  That is radically different from what I was seeing locally.  It gets even worse sometimes:
screen shot 2017-04-14 at 12 32 16 pm

I will investigate.

**Comment by gabycampagna** [comment]
Oh wow!  I wasn't sure if I was missing something. It flickers too on hover. If you keep the mouse still it is ok, but soon as you hover it blinks/flickers.  Thanks!

**Comment by gabycampagna** [comment]
The line chart is missing elements too.
screen shot 2017-04-14 at 1 32 16 pm

**Comment by jrjohnson** [comment]
@gabycampagna this is ready to review again.

**Pull request merged**
