### PR TITLE
course manager: restrict user search for directors by role

### PR DESCRIPTION
**Pull request by stopfstedt**
only course directors should be included in search results.

### CODE REVIEW

**Comment by stopfstedt** [comment]
refs ilios/ilios#1074.

**Comment by jrjohnson** [comment]
:+1:  just waiting for tests to pass

**Comment by saschaben** [comment]
check line 63 of user.js:

File: ilios/components/user-search.js
ilios/components/user-search.js: Unexpected token (63:45)
SyntaxError: ilios/components/user-search.js: Unexpected token (63:45)
  61 |       if (this.get('roles')) {
  62 |         query.filters = {
> 63 |           roles: this.get('roles').split(',');
     |                                              ^
  64 |         }
  65 |       }
  66 |       this.get('store').query('user', query).then(users => {

**Comment by stopfstedt** [comment]
@jrjohnson fixed tests, this is ready for review. thanks!

**Comment by jrjohnson** [comment]
@homu r+

**Pull request merged**
