### PR TITLE
Add School Leadership

### LINKED ISSUE #2362: Add 'X Leadership' user mgmt section for each user type in permissions table
Per the 11/17/2016 codejam discussion, we need to add the ability to view and manage users in all relevant areas of the interface (eg, 'Course Leadership', 'Session Leadership', 'Program Leadership', and 'Program Year Leadership').

This section should mimic/resemble the already-existing 'Objectives' sections: collapsed by default, with summary of current membership shown. (Something like the attached image) below:
session_leadership_collapsed  

Add 'Manage' link to summary, which would expand the section and offer search box(es) for adding/removing of personnel.

### PR DESCRIPTION
**Pull request by jrjohnson**
WIP needs:
- [x] Some components should be more generic
- [x] Loading state indication for admins / directors
- [x] Tests
- [x] Fix save - it doesn't close the panel
- [x] Replace summary with an actual summary 'there are 2 directors', 'there are 0 administrators'
- [x] Translations

Fixes #2362

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 163112864113e8405cd354e7e8dab49a10f0bd01

https://deploy-preview-2404--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
I'm assuming I'm not testing functionality here ( there are problems with firing a save after initial load); but for search layout: OK. Not in love with the header bar as it is right now when in edit mode...Thinking we may want some further visual demarcation as well for the two search boxes...but generally I think the patter works for search and add. However, we def. need it to function more fluidly for save / state change.

**Comment by jrjohnson** [comment]
@saschaben this is ready for review again with just some tests left to write.

**Comment by jrjohnson** [comment]
List alignment fixed.  Ready for review again.

**Pull request merged**
