### PR TITLE
Recurring Events

### LINKED ISSUE #1326: Replace "Recurring Event" option for offerings
This is functionality which was dropped in the conversion due to it being buggy as sin in previous releases; unfortunately it appears to be a critical need for the users.

Recurring events allow for:
1. the creation of multiples of a given offering, 
2. the cloned offerings take identical associations as the original which spawns them
3. events can be set to occur on a given day or days of the week, for a specified number of events
4. or a specified number of weeks
5. Recurring events do not need to be chained or tracked as a set, but if it were possible to allow for that (as very low hanging fruit), I wouldn't cry.

### PR DESCRIPTION
**Pull request by jrjohnson**
Supersedes #1387
Fixes #1326

- [x] Figure out validations
- [x] Write tests
- [x] Review changes post rebase (which was messy)

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this is now ready for functional review.

**Comment by saschaben** [comment]
Attempt to de-select current day as a recurring option fails:
> open recurring.
select sunday.
de-select thursday.
set weeks to 3.
save.

you will generate 6 offerings, 3 for sundays and 3 for thursdays.

**Comment by jrjohnson** [comment]
@saschaben ready for another test.  I locked whatever the start date of the offering in as one of the selected days for recurrence and disabled the checkbox.  Is it clear what is happening or do we need more user guidance here?

**Comment by saschaben** [comment]
This looks good to go now functionally.

This branch is still broken viz. adding new session/manipulating course level items.

**Comment by jrjohnson** [comment]
@saschaben please test again - I think I have this all fixed now.

**Comment by saschaben** [comment]
:+1: 
all good. rock n roll.

**Comment by stopfstedt** [comment]
reviewed, LGTM :+1:

**Pull request merged**
