### PR TITLE
Save learning material notes correctly

### LINKED ISSUE #714: Course and Session learning material notes are not saving
References https://github.com/ilios/ilios/issues/845

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #714

### CODE REVIEW

**Comment by saschaben** [comment]
a thing currently failing in local fakeAPI builds, but not yet tested in API builds: when notes exist, this is not being correctly identified in the list view (label remains "no" rather than shifting to a nice green "yes"). let's make sure this gets validated with this PR

**Comment by jrjohnson** [comment]
@saschaben That indicator is attached to the showNotes option.  Do we want to modify the columns to be something like:
- Show Notes
- Has Notes

and then have both indications?

**Comment by saschaben** [comment]
@jrjohnson I think it better that we leave it as is for now and merely detect note existence with yes and no. We should add an enhancement to update the display to include an additional icon flag for when they are either hidden or shown (maybe along the lines of the eyeball or some such).

**Comment by jrjohnson** [comment]
Further work in #720.  This can be merged.

**Pull request merged**
