### PR TITLE
adds term counts to vocab and term manager.

### LINKED ISSUE #5752: Provide Counts of Sub-Terms in Vocabulary Management
Terms can be nested below the highest level.

image

After clicking as shown above, the user receives the following information. As shown above, there are 7 terms / sub-terms in this vocabulary.

image

There is no way a user would know where the nested terms are nested. There should be numerical indicators to help with this task. 

Something like ...

image

Here it is drilled down another level - this should apply at every level of navigation.

image

We also need to verify the counts are correct - I was only seeing six sub-terms in this example. Anyway it would be helpful.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #5752

### CODE REVIEW

**Comment by dartajax** [comment]
Is there any possibility of not showing the sub counts if the answer is zero like in these cases?

image

**Review by dartajax — CHANGES_REQUESTED** [review]
image

**Comment by stopfstedt** [comment]
@dartajax - how's this?

image

**Review by dartajax — APPROVED** [review]
looks good to me

**Pull request merged**
