### PR TITLE
Align models with API

### PR DESCRIPTION
**Pull request by jrjohnson**
This updates the models to match the API in ilios/ilios#1106

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this probably needs a click around test to make sure nothing unexpected broke.  I caught at least one problem with changing a session's type.

**Comment by saschaben** [comment]
When attempting to add a parent objective to a course objective, getting a `403 forbidden` (using http://localhost:4200/api/v1/objectives/77716, on localhost:4200/courses/791)

Attempting to save a cohort to a course returns a 403 as well ( course 791, cohorts 66, 17)

attempting to create a new small groups set or offering returns a 403 (courses/791/sessions/23044)

saving learning material from search returns 403

**Comment by jrjohnson** [comment]
:+1:  I've created tickets to handle the remaining issues:
ilios/ilios/#1118
ilios/ilios/#1119

@thecoolestguy please review code and merge.

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
