### PR TITLE
removed file-upload deprecation

### PR DESCRIPTION
**Pull request by djvoa12**
Deprecation Warning:
- Observing the `files` attr is deprecated, use `filesDidChange` instead.

### CODE REVIEW

**Comment by djvoa12** [comment]
@jrjohnson need help verifying this code works. It let me upload a simple text file, but it returns server error when I click on the link to the uploaded file, which I assume it's for direct download.

**Comment by jrjohnson** [comment]
I think problems testing are related to https://github.com/ilios/ilios/issues/1190

**Comment by jrjohnson** [comment]
This will require #1230 to be merged so it can be tested.

**Comment by jrjohnson** [comment]
:+1: works!  @homu r+

**Pull request merged**
