### PR TITLE
Copy sessions into another course

### LINKED ISSUE #1509: Functionality Needed For Session Copy Into Same Or Different Course
We need to make it possible to copy a session (with or without the offerings) into (by default) the same course or into a different course of the user's choosing.

It would copy all of the attributes of the original session (MeSH, Vocabulary, etc.).  If copied into the same course, a "(2)" would be appended to the session title.  It would then be up to the user to update all of the details of the cloned session.

### PR DESCRIPTION
**Pull request by jrjohnson**
Copies the session with no offerings, but all other metadata, into
another course.

Fixes #1509

WIP: 
- [x] Translations

@saschaben this is ready for review, especially re the placement of the copy link.

### CODE REVIEW

**Comment by saschaben** [comment]
target course list is not complete: is truncated at 20 course values. should list ALL courses for the selected year, including draft courses.

**Comment by jrjohnson** [comment]
Session objective are not copying correctly and carrying mesh descriptors.  Still need to work on this.

**Comment by jrjohnson** [comment]
@saschaben ready for another review.  Should be copying session objectives correctly now including their mesh terms, but not their linked course objectives.

**Comment by saschaben** [comment]
👍

**Comment by stopfstedt** [comment]
LGTM

**Pull request merged**
