### PR TITLE
No curly invocation

### PR DESCRIPTION
**Pull request by stopfstedt**
code cleanup, prep-work for octanification.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@dartajax needs a bit of click around testing to spot anything weird, otherwise this is ready to merge.

**Comment by jrjohnson** [comment]
This is probably resolved by https://github.com/ilios/common/pull/1254 so we'll need to update common here before merging this.

**Comment by dartajax** [comment]
Other click events don't work either - like clicking on the Ilios menu to navigate to Courses and Sessions or Learner Groups.

**Comment by stopfstedt** [comment]
> Other click events don't work either - like clicking on the Ilios menu to navigate to Courses and Sessions or Learner Groups.

thanks, looking into it...

**Comment by stopfstedt** [comment]
@dartajax non-working menu links  - that's a side effect of the broken click-through to calendar event details. it breaks routing. unrelated.

**Comment by stopfstedt** [comment]
@dartajax this is ready for re-review. the calendar issue has been fixed via #5216 and incorporated into this branch. please have another go at this, thanks!

**Pull request merged**
