### PR TITLE
Calendar Updates

### LINKED ISSUE #941: Calendar Day View cuts off at 4pm
This disallows the view of any activity 5pm or on. Need to add a vertical scroll just as with week view. or make overflow visible. or somethin'.

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #941 #977 #930

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this is ready to review and can be tested against demo or stage.

**Comment by saschaben** [comment]
on show all calendar for november 8,9,10, getting the `TypeError: Cannot read property 'totalLevels' of undefined` error. nothing shows in network tab; think this may be either bad data or we are pulling a deleted event....?

**Comment by saschaben** [comment]
on the upside: ics thing seems to be perfect. ILM views now appear to be working (though we are indeed setting them to 4pm rather than our previous 5pm, not a big deal but weird); and everything else is pretty much passing muster as far as I can tell.

**Comment by jrjohnson** [comment]
- 1 Existing issues caused by the Valour Lunch course which goes from August to June.  (#1068)
- 2 We've never had the user events on the show all calendar.  My solution would be to rename that switch to 'School Events' - does that work?  Or do we need to combine the user and school events onto the same calendar?
- 3 I'm having trouble reproducing this.  Might it be related to 1 (in that the bug there broke going back)?
- 4 new ticket #1069

**Comment by saschaben** [comment]
- 1 Existing issues caused by the Valour Lunch course which goes from August to June.  (#1068)
> - OK. I missed that one. Is there a possible fix for this (otherwise we're gonna very quickly have some negative feedback from our VALOR students & faculty)

- 2 We've never had the user events on the show all calendar.  My solution would be to rename that switch to 'School Events' - does that work?  Or do we need to combine the user and school events onto the same calendar?
> - Wow. Never mind. I just wrote a big o'l response to this but as I stepped thru to validate the use case to reproduce,  I found that the error is actually an artifact of the bug reported in #1. The correct items show if the display is not busted by the multiday event (in which case NOTHING shows. Suckity suckity.)

- 3 I'm having trouble reproducing this.  Might it be related to 1 (in that the bug there broke going back)?
> -  I don't think so. To reproduce: proxy to demo3. login as demofaculty3. open calendar to show all events. toggle to view Pharmacy. click on Monday 11/9 "Quality  Assurance/Improvement" 10am. Hit back button in the browser (or keyboard). dahsboard will load the calendar for Medicine.

- 4 new ticket #1069 
> - Yay. Boo.

**Comment by jrjohnson** [comment]
AH!  The School!!  I was thinking the all evens slider.  I have no idea why I couldn't make that connection.  Yea.  School isn't sticky.  It really should be.  I created a new issue for this #1070

**Comment by saschaben** [comment]
:+1:

**Pull request merged**
