### PR TITLE
Add user from the directory

### PR DESCRIPTION
**Pull request by jrjohnson**
When a directory is available on the API server users can be looked up and added from that directory instead of being entered manually.

WIP: Needs translations and some tests.  

@saschaben please check the overall functionality of this approach.

### CODE REVIEW

**Comment by saschaben** [comment]
unable to test on proxy. getting content security protocol violations on ember serve, and 500 errors when navigating to admin tab.

**Comment by saschaben** [comment]
ok. Proxy running -- and all looks good in the user admin world, but AFAIK we don't have a directory connection on Demo, and so don't have a feed to test against for functionality...

**Comment by saschaben** [comment]
Looks great. Functionally we are good for a merge with additions in the next iteration. for this PR:

- [ ] remove the inner box that is displaying around search results (or shorten it so it does not overrun the header on search results). It looks weird.
weird

- [ ] add some padding to the top of the results form:
addpad

- [ ] remove the sticky search term.
- [ ] on `cancel`, the search/add manager should not collapse.

In the next round, we will address the selection of `is/is not student` and the default addition of role(s).

**Comment by saschaben** [comment]
additional UI tweaks: 

morepadding

onemore

**Comment by dartajax** [comment]
We have those yellow boxes in other places that we should get to removing as well.

**Comment by jrjohnson** [comment]
Ready for review again.

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@stopfstedt tests are passing - this is all yours for review.

**Comment by stopfstedt** [comment]
:+1: LGTM

**Pull request merged**
