### PR TITLE
Add the ability to lock and unlock courses

### PR DESCRIPTION
**Pull request by jrjohnson**
On the course list clicking the lock icon locks or unlocks the course if
the user has permission to do so.

Removed the edit icon in order to make space (also it doesn’t do anything)
Moved lock and delete into the status column along with publish for a little bit nicer visual picture.

WIP:
- [x] Needs API change to allow course unlock
- [x] Needs tests for lock /unlock on course list
- [x] Add lock to program year list
- [x] Only developers can unlock - need to enforce this in the UI

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this is now ready for review for locking courses and program years.

**Comment by saschaben** [comment]
getting there.

The good:
> Lock/unlock looks good, permissions appear good. Yay!

The less good:
> 1: Locked courses still allow for the addition/modification of session objective mesh terms. Boo!
> 2: Locked program years still allow for management of all manageable sections. Double Boo!

**Comment by jrjohnson** [comment]
@saschaben I created new issues for being able to edit these locked things.  Can you prioritize them?  Since they are existing issues I think we should go ahead and merge this as is.

**Comment by saschaben** [comment]
@jrjohnson sounds good. with the new tickets added, this is ready for code review.

**Comment by thecoolestguy** [comment]
@homu r+

**Pull request merged**
