### PR TITLE
Create new courses with a form

### LINKED ISSUE #48: New course creation needs work
When clicking new course button on /courses:
[ ] Fix title translation to have some content
[ ] Fix start / end dates to have content
[ ] When the course detail page open the title edit box should be open and focused
[ ] The default title should be "Add Course Title: YYYY-MM-DD hh:mm:ss"

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #48

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/215" target="_blank">ReviewNinja

**Comment by saschaben** [comment]
notes:
1: Yay!
2: padding needed between year select and buttons
3: after course is instantiated, there is no form entry field / prompt for external ID.

**Comment by jrjohnson** [comment]
@saschaben fixed the issue with external ID.  The styling stuff we should merge first and then take a look at that.  I structured it to be style-able.

**Comment by saschaben** [comment]
Required fields are required: currently you can create a course with no title.

**Comment by jrjohnson** [comment]
No validations right now.  We will add those in #198

**Comment by jrjohnson** [comment]
@saschaben I rebased this so it can now be merged. @thecoolestguy already checked the code, merge it if it works.

**Pull request merged**
