### PR TITLE
Add info to the course detail session list.

### LINKED ISSUE #53: Fix content on course detail session list
The list rows do not currently display most of the required count content.

### PR DESCRIPTION
**Pull request by jrjohnson**
fixes #53

### CODE REVIEW

**Comment by saschaben** [comment]
Appears to be intermittently failing to load session type -- about 40-50% of sessions. no rhyme nor reason to it from the UI side.

**Comment by jrjohnson** [comment]
@saschaben check this now, problems with session type should be resolved.  
@jenzweben - I changed the first offering from the mock to include the time and not just the date since I figured thats what people would want to know.  Is that correct?  Or should it just be mm/dd/yyyy as in the mock?

**Comment by jenzweben** [comment]
Where should I be viewing the changes you made?

**Comment by saschaben** [comment]
@jrjohnson @jenzweben I think the timestamp addition to the date will be welcome by the users. It makes it a little more busy / messy than the mock, but I think the value will outweigh the issue

**Comment by jenzweben** [comment]
OK

**Pull request merged**
