### PR TITLE
Add Instructor Group landing page

### LINKED ISSUE #461: Create Instructor Groups Landing Page
instructor-groups-landing-v3

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #461

### CODE REVIEW

**Comment by saschaben** [comment]
Excellent. The "Remove" notice requires style/formatting correction, not sure is this is a follow-on or a correction for this PR.

**Comment by jrjohnson** [comment]
@saschaben - I fixed the remove notice - give that another look.

**Comment by saschaben** [comment]
Looks good. Question: do we need to have School as a column, since instructor groups are school-specific? Assuming we have a school drop-down, I don't think we need a school column.....

**Comment by jrjohnson** [comment]
Ha.  I was going to say I just did it like the mocks - but they have no school - I obviously hallucinated that.  I will remove the school column and update.

**Comment by jrjohnson** [comment]
OK - back again.  This time with no schools column.

**Comment by saschaben** [comment]
OK. Full marks. Please ninja star and merge!

**Pull request merged**
