### PR TITLE
Enable embroider

### PR DESCRIPTION
**Pull request by jrjohnson**
Tests are passing and everything appears to be working, let's turn this on and see how it works.

Issues:
- [x] https://github.com/ilios/ilios/issues/4508

### CODE REVIEW

**Comment by jrjohnson** [comment]
I'm seeing a speedup of 1-4 seconds loading time on 4G simulated network and several megabytes less javascript. Even compressed it's 500K less JS shipped. Yay. @dartajax please test this netlify build for any weirdness. Initial load and speed for students should be significantly improved.

I'd like to test on a variety of devices and with several users so let's not merge this yet, but it's ready for that testing in my opinion.

**Comment by dartajax** [comment]
This is not a review but merely a comment. This PR acts weirdly if the session gets stale like when you go eat lunch and come back, which is what I did. I even raised a sentry upon rage-clicking after eating my lunch. @jrjohnson may want us to continue testing on this.

**Comment by dartajax** [comment]
Except for my previous comment, my testing has gone fine on this PR - added `DO NOT MERGE` just so we don't accidentally force this through - more review / testing is still necessary.

**Comment by jrjohnson** [comment]
@dartajax ready for another review, still in the do not merge status, but if it checks out we may be ready to merge this week.

**Comment by dartajax** [comment]
image

image

**Comment by dartajax** [comment]
I was testing against demo with my screen shots above. It turns out I should have been testing against our current netlify build. The current netlify build has the same issue as the screen shots above; therefore, this issue is not related to this PR but is another issue we will need to fix once these changes have been pushed up to demo, which they have not been pushed to ... yet.

**Review by dartajax — APPROVED** [review]
so far so good - I plan on testing this more still but it seems fine to me

**Comment by jrjohnson** [comment]
@dartajax when you feel like this has been well tested it's ready to merge! 🎉

**Pull request merged**
