### PR TITLE
Move school out of detail view - apply mixin styles

### LINKED ISSUE #2377: school details style cleanup
Refs #1705

### PR DESCRIPTION
**Pull request by jrjohnson**
Part of the process of removing the .detail-view css class which is
inherited too often.

Fixes #2377

WIP:
- [x] Review new style for needed changes
- [x] Fix any tests which are now out of whack.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 38f924f88efb921908b512916e5570d07b2b4820

https://deploy-preview-2384--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
@saschaben please take a look at school management and let me know if this style is OK.

**Comment by saschaben** [comment]
Looks pretty good; the only thing I note is the misalignments shown below for competency domains with titles long enough to wrap. In these grids we should make sure all text is top aligned. Also, if we can increase the gutter space between "domain" and "summary" columns by a hair, that might be good to:

align1
align2

**Comment by jrjohnson** [comment]
@saschaben this is ready for another look.

**Comment by saschaben** [comment]
netflify deploy preview is failing

**Comment by jrjohnson** [comment]
Wow.  Failing hard too!  I will investigate.

**Comment by saschaben** [comment]
big thumbs up on the formatting. 👍

**Pull request merged**
