### PR TITLE
refactored events route use authn route mixin.

### LINKED ISSUE #1936: Events route not bouncing unauthenticated users
If you visit the /events/ route without being logged in you will get a weird error because it attempts to get data from the API instead of forcing authentication first.  This route just needs to extend the `AuthenticatedRouteMixin`

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1936

### CODE REVIEW

**Comment by saschaben** [comment]
is this ready for review eyeballs and merge?

**Comment by stopfstedt** [comment]
@saschaben ready for review.

**Comment by saschaben** [comment]
LGTM 👍

**Comment by saschaben** [comment]
please code review and merge

**Pull request merged**
