### PR TITLE
Remove un-postable fields from learning materials

### LINKED ISSUE #875: Unable to save a citation as a new course learning material

### LINKED ISSUE #957: Unable To Add Learning Material To Session (ILM)
https://ilios3-demo.ucsf.edu/courses/812/sessions/24354

I tried to upload a file from my own computer - a nice picture of me riding my scooter in a parade and got the following error ...

addnewlmtosession

Here's the shot from the parade ...

parade1

### LINKED ISSUE #1007: Unable To Edit / Update Learning Material
Click on "test" to edit LM data.  This is Course level LM.

lm1

lm2

lm3

lm4

lm5

lm6

lm7

Refresh and check -- the update was saved.

lm8

### PR DESCRIPTION
**Pull request by jrjohnson**
This should allow course and session learning materials to be saved.

Fixes #1007
Fixes #957
Fixes #875

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben please review against demo API.

**Comment by saschaben** [comment]
Files: __OK__
Citations: __OK__
Weblinks: __*FAIL*__

check for issues with upload of weblink.

**Comment by jrjohnson** [comment]
@saschaben links work for me as long as they are valid.  What URL did you try to add?  Its possible that symfony is stricter about matching URLs that we want it to be.

**Comment by saschaben** [comment]
@jrjohnson I'll check again for you; was using "www.google.com"

**Comment by jrjohnson** [comment]
Yup, turns out you need the http:// on the link.  We can probably deal with this in validation with a nice message or else we need to change the validator on the API to not enforce correct URL.  Either way this isn't something to fix in this PR.  Whichever way you want to go should get a new ticket.

**Comment by saschaben** [comment]
OK will write it up now.

**Comment by saschaben** [comment]
OK within the current constraints. But please see #1013.

**Comment by saschaben** [comment]
:+1:

**Pull request merged**
