### PR TITLE
added empty list and search results handlers

### PR DESCRIPTION
**Pull request by djvoa12**
**Summary:**
Added empty list and search results handlers for ...
- Courses and Sessions
- Instructor Groups
- Programs
- Curriculum Inventory

**UI:**
_Empty List:_
Screen Shot 2019-04-08 at 5 25 18 PM

_Empty Search List:_
Screen Shot 2019-04-08 at 5 26 27 PM

Fixes https://github.com/ilios/frontend/issues/4479

### CODE REVIEW

**Comment by dartajax** [comment]
image

**Comment by dartajax** [comment]
image

**Comment by dartajax** [comment]
The same is true at least while searching on Courses and receiving the `No Results Found` message - it should be under `Course Title` and not under `Level`

**Comment by dartajax** [comment]
so left justify instead of center alignment would be better I think

**Comment by djvoa12** [comment]
I think it looks way better centered. Left-aligned looks weird. Center would stay true as the screen size collapses.

**Comment by dartajax** [comment]
?
image

**Comment by dartajax** [comment]
However ...

image

It should look more like this in that case ...

image

The label No Results Found should not affect the column headers.

**Comment by djvoa12** [comment]
@dartajax I fixed the responsive columns issue.

**Comment by stopfstedt** [comment]
superseded by #4492

**Pull request closed without merging**
