### PR TITLE
Fix broken publish and schedule functionality

### PR DESCRIPTION
**Pull request by jrjohnson**
The publish event was never getting saved so nothing was getting
published.

### CODE REVIEW

**Comment by saschaben** [comment]
This looks to be solid so far from the UX side; testing proxied against demo means not being able to verify the data in the publish_event table vs. the course/session tables, but functionally this appears to be on it.

**Comment by saschaben** [comment]
:+1:

**Comment by saschaben** [comment]
@jrjohnson if this is ready now with the test modification for merge, let me know. (You still have it tagged as 'in progress')

**Comment by jrjohnson** [comment]
Waffle does that tagging.  It's ready as far as I am concerned.

**Pull request merged**
