### PR TITLE
changed default switches

### LINKED ISSUE #1018: Show Notes to Students Should Default to True / Yes
This is for adding Learning Materials to a Course or Session.  It is during the second step of the process (after the LM has been attached to the Course or Session) that this takes place.

The default should be to show the notes to the students since this is by far the most commonly used option.

studentnotesyes

### LINKED ISSUE #1045: Required Should Default to Yes / True with Learning Materials
Related to #1018 in a way because this is just another toggle in the same location.

The required flag should be set to Yes / True by default as shown below.

image

### PR DESCRIPTION
**Pull request by djvoa12**
Fixes #1018
Fixes #1045

### CODE REVIEW

**Comment by saschaben** [comment]
:+1:

**Comment by jrjohnson** [comment]
@saschaben please take a look again.

**Comment by saschaben** [comment]
:-1: 

working for course learning materials, but not for session learning materials.

**Comment by saschaben** [comment]
:+1:

**Pull request merged**
