### PR TITLE
prevent program years with populated cohorts from being deleted.

### LINKED ISSUE #2237: don't show delete button for program years with populated cohorts.
the backend will reject cascading deletes of program years on the cohort-to-user join table.

put a check into the frontend that controls the display of the delete button based on existing cohort/user relationships.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2237

### CODE REVIEW

**Comment by stopfstedt** [comment]
ready to be click-tested, still working on acceptance tests.

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 57f192107b7b94d975fd5986adc0e401f0970cc3

https://deploy-preview-2281--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
hhmm. seems to be working, but in the case where a PY without cohort members gets published,  then unpublished, it is requiring a hard refresh for the delete icon to return.

**Comment by stopfstedt** [comment]
@saschaben acknowledged, but that's a different issue. filing bug report on this now.

**Comment by saschaben** [comment]
in that case, :+1: !!!!

**Pull request merged**
