### PR TITLE
Working dashboard calendar

### LINKED ISSUE #708: Basic Calendar display on dashboard
Some kind of calendar is required on the dashbaord.

### PR DESCRIPTION
**Pull request by jrjohnson**
This is a first draft functional calendar to give us something to iterate on.  
Fixes #708 

Are there things that needed to be added to make it minimally viable before it can be merged?

Todo:
- [x] Update to elemental-calendar 0.0.4 (when it is released)
- [x] Figure out what we need to test and write tests
- [x] weekview date headers all display dayOfWeek as Today
- [x] Day view is not displaying any event data
- [x] Add location to event blocks
- [x] add classes / colors to events
- [x] Start the week list at 8am or the first event
- [x] Fix overflow at the bottom of a week (see screenshot)
- [x] Temporarily remove the month view
- [x] Format event text
- [x] Return to using official library
- [x] Switch Date URL to YYYYMMDD from DDDYYYY
- [x] In the week view differentiate days with vertical stripe or border
- [x] Create event component which shows our values (Start Time, Location, Title)
- [x] Month event component should be different in that it truncates title to fit on a single line

### CODE REVIEW

**Comment by saschaben** [comment]
Issues:
1.  weekview date headers all display dayOfWeek as Today:

weekview header1

2. Day view is not displaying any event data
3. Month view currently scrolls events as well as the numerical date value -- this will be unusable. The date value in each daybox section of the month view must be static, with content scrolling (if we scroll rather than expand) beneath it.
4. display data needs to be ordered so to provide the user with value data first:
   a: TIMEBLOCK/DURATION
   b: LOCATION
   c: TITLE
5. we really need to get the colors for events displaying as well, otherwise it will freak out users even in prerelease.

**Comment by saschaben** [comment]
If we can't sort out the month view grid issues, we should move ahead with only day/week views (and the default non-calendar "event list" view), and work on it further. 

A typical month-view user is a DIRECTOR or INSTRUCTOR or DEAN.
A typical day will have 1-3 events for a given user.

**Comment by saschaben** [comment]
here's a quick crap rendering of what we need to get closer to for release. text has been formatted to 500 wt. at 0.65em; solid white top and bottom border has beed added to break up events in a day. 

monthviewtextstyled

and a detail shot (again, craptastic but just to get us pointed in the right direction:)
monthdetail

**Comment by saschaben** [comment]
if we can get the CSS mapped out to provide discrete day locks with scroll, and get the correct data showing, we'll be on the way.....one more crap modeling:
monthview3

**Comment by saschaben** [comment]
Just to be clear -- MVP for a first draft should address the numbered list items above. Everything else is to provide pointers for where we need to go beyond minimum viability for the first draft, to get us to a functional calendar.

**Comment by saschaben** [comment]
love the checklist functionality!

**Comment by jrjohnson** [comment]
@saschaben - this is ready to test again.  The only big issue outstanding is stacking events when they occur at the same time and @ebryn and co are working on that.

**Comment by saschaben** [comment]
This is looking great. The issues I still see:

1. navigation does not appear to be working -- I can't get anywhere other than day = today (6/16), week starting 6/14, or month June.
2. Start the week list at 8am or the first event is still wonky -- since there are events dripping over from previous day that display thru 1am (and this looks to be a UTC rendering bug we will have to sort out, but that for later), the display continually flashes momentarily to the first "normal" time block event, then instantly rolls back to midnight. If we can't easily get this sorted, better to just hard code a default of 8am.
3. we still need a padding space between events; a <3px white border-bottom for the event class should take care of this.

**Comment by saschaben** [comment]
Also, just noticed we have forgotten to display the current year for the display. Not sure if we should handle this in application or calendar, but see mockup for expectations in #206

**Comment by saschaben** [comment]
getting so close!

We appear to not be converting UTC values in the db to localized timezone values on the UI. Not sure if this is an API thing, a calendar/ember thing, or what, but we definitely should fix prior to launch.

**Comment by jrjohnson** [comment]
@saschaben - once again ready for review. Couple of additions in addition to the new styling:
- Month days now scroll as desired
- Activated links on a month day and a week header to go to that day

**Comment by dartajax** [comment]
I am going to watch that deploy you requested @jrjohnson and hopefully it will enable me to test this easily as well.

**Comment by saschaben** [comment]
:+1: 
The scroll still isn't ideal in month, provides some weirdnesses when screen is reduced in size, but....should be good enough for this release. Still a number of tweaks needed in styling: we need to add a scroll to day/week view events (anything less than an hour in length is getting cut off and hidden), need to work on horizontal expansion or fitting for week view when we have words that are longer than there is horizontal space in the column (could do scrolling, I suppose, but I hate horizontal scrolls like that), but.....

if we add the scroll (overflow-y) to day/week events, I think we can ship now.

**Comment by saschaben** [comment]
OK. This round is awesome. I DO love it. But....
the 2rem margin-bottom on events class doesn't seem to be doing it for me. padding-bottom:4rem definitely does. I fear we need to make that modification -- the invisibility of events is a scary notion to start out the gate with.

Otherwise, my only curiosity is about side by side events: right now it looks like we are making the width calculation globally for all events in a block. I am wondering what happens when a viewer would look at a day with 24 simultaneous small groups at 3-4pm sandwiched between a single lecture at 2-3pm and a single exam at 4-5pm using this calculation method....something to discuss with Erik AFTER this push.

Move this along -- code review and MERRRRRRRRGE

**Comment by saschaben** [comment]
this is good to go for 0.3.0

**Pull request merged**
