### PR TITLE
replace jshint with eslint

### PR DESCRIPTION
**Pull request by Trott**
Replace `jshint` with `eslint`. 

Add linting to `npm test`. 

Partially addresses #1363. 

There are a bunch of comments in tests/acceptance/learnergroup/membership-test.js that look like are documenting JSLint issues or something? Wasn't sure what to do with those.

/cc @stopfstedt @jrjohnson

### CODE REVIEW

**Comment by Trott** [comment]
Finished this up, did a rebase to squash commits and then a force push. I've removed the `in progress` label.

**Comment by Trott** [comment]
If you want to see the changes with whitespace-only changes excluded: https://github.com/ilios/frontend/pull/1366/files?w=1

**Comment by Trott** [comment]
CI is green!  \m/

**Comment by jrjohnson** [comment]
Needs a change to .travis.yml as well - should either go back to running tests using `npm test` or else add eslint as an additional test.  I think now that we have stopped running browser specific sauce labs tests that going back to `npm test` is the right move.  That should run phantomJs as that is the CI test specified in testem.json.

**Comment by Trott** [comment]
`.travis.yml` updated and pushed

**Comment by Trott** [comment]
OK, now it's trying to run `eslint` on `travis-phantom`. I guess I could add `travis-phantom` to `.eslintignore` but I'd prefer it just not be in `pwd` at all. So let's try moving it...

**Comment by Trott** [comment]
commit pushed, build in progress, hope I got it right the first time...

**Comment by Trott** [comment]
OK, that worked. Will squash those last three commits down to one and force push. That will probably trigger another CI build, but hey, why not?

**Pull request merged**
