### PR TITLE
Move to Fontawesome 5

### LINKED ISSUE #1864: Icons periodically disappear
Sometimes icons seem to go away, and then after a while they come back.
missing ilios 3 icons

### PR DESCRIPTION
**Pull request by jrjohnson**
This is going to be a work in progress, needed a place to test and to run tests.

Fixes #1864

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 801187aae03164e6d2c07fd0db61d2494b5a89f1

https://deploy-preview-3566--ilios-frontend.netlify.com

**Comment by saschaben** [comment]
delete icon in instructor group name labels is fekakdeh:
fontawesome

**Comment by saschaben** [comment]
Additional notes:
fontawesome2
fontawesome3
fontawesome5

**Comment by jrjohnson** [comment]
Addressed the missing nav icon and the spacing issue. The missing LM icons will need to be fixed in common if we come closer to a release.

**Pull request merged**
