### PR TITLE
Display the groups associated with courses and sessions

### LINKED ISSUE #204: Display associated groups in course overview
JZ will create mock

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes #204

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ilios/frontend/pull/281" target="_blank">ReviewNinja

**Comment by thecoolestguy** [comment]
needs rebase... there are some merge conflicts.

**Comment by thecoolestguy** [comment]
ninja-starred for code... Merge when functionality verified...

**Comment by jrjohnson** [comment]
@saschaben - this is now rebased and ready to merge.

**Pull request merged**
