### PR TITLE
Update the user profile page

### LINKED ISSUE #2026: Update the MyProfile page
refactor this page to provide discrete sections for managed editing, better layout, and more logical structure and data transaction management.

will include:
- [x] general user identifying information
- [x] role information
- [x] cohort assignment information
- [x] learner group assignment information
- [x] status information (enabled/disabled, former student)
- [x] username & password management for non-SSO/LDAP schools
- [x] calendar feed management
- [x] ~~API token management~~ (too much power, need to discuss)
- [x] single user sync
- [x] Fix style for pending user updates box
- [x] When pending user updates fires an action the user roles box should update as well
- [x] When pending user updates fires an action the user bio box should update as well
- [x] Clear user search when a choice is made
- [x] Indication of being disabled by user name
- [x] Display primary school and have the ability to add secondary schools

### PR DESCRIPTION
**Pull request by jrjohnson**
Improved user profile editing and management.

Fixes #2026

Group review notes:
- [x] Change from disable user to 'Account Enabled'
- [x] should say 'none' when no cohorts in school when managing secondary cohorts
- [x] more spacing between two icons in secondary cohort list and between remove icon and the cohort name
- [x] use the course section heading blue on primary / secondary cohort heading
- [x] use the same blue for all headings on the user profile 
- [x] lets make it the default color for all ilios-heading elements on the site
- [x] lets use two translatins for ICS calendar instructions
- [x] Update the username when we sync - show the username on the bio page even when it cannot be updated.
- [x] Sort out blinkey checkboxes when roles are updated

### CODE REVIEW

**Comment by jrjohnson** [comment]
@saschaben this is now ready for review as I believe it is done.  The only work left to do is translations and some test cleanup.

**Comment by saschaben** [comment]
TESTING NOTES:
1) user should not be able to disable their own account.
2) getting occasional 500 empty payload errors when changing permissions; could be a timing issue on the API? Perhaps build in a 1-second wait time?

**Comment by dartajax** [comment]
Not a big deal but when you click the "Account Enabled" or "Exclude From Sync" check boxes, the two that are already checked as shown blink really quickly.  It made me wonder (as a user) if I had done something.  They should not blink like that.

image

**Comment by jrjohnson** [comment]
@saschaben and @dartajax please take yet another look and let me know if you see any additional issues.

**Comment by saschaben** [comment]
LGTM 👍 

let's get this code reviewed and merged!

**Comment by jrjohnson** [comment]
I have done my best to review my own code here and it LGTM 👍

**Pull request merged**
