### PR TITLE
normalized line-height for Course Descriptions and Parent Objectives

### PR DESCRIPTION
**Pull request by michaelchadwick**
Fixes ilios/ilios#3802

### CODE REVIEW

**Review by jrjohnson — APPROVED** [review]

**Review by dartajax — DISMISSED** [review]
image

**Comment by michaelchadwick** [comment]
@dartajax Is the problem that there is space around that first description? Or that the first Parent Objectives column is too wide? Regardless, demo does that, too, and is a new bug to fix: https://demo.iliosproject.org/courses/2224?courseObjectiveDetails=true&details=true

**Comment by dartajax** [comment]
> @dartajax Is the problem that there is space around that first description? Or that the first Parent Objectives column is too wide? Regardless, demo does that, too, and is a new bug to fix: https://demo.iliosproject.org/courses/2224?courseObjectiveDetails=true&details=true

I am fine with filing the new issue and will do so soon. I think it has to do with the fact that that one course objective was using the numbered list inside of the froala text box. Maybe when calculating the width of the content, the indentation caused by the use of the list is causing issues - something like that.

**Comment by michaelchadwick** [comment]
@dartajax All tests now passing

**Pull request merged**
